// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class ButtomNaviCompComponentHandle extends ffai.ProjectComponentHandle<ButtomNaviCompParams, ButtomNaviCompState> {
  ButtomNaviCompComponentHandle()
    : super(
        name: "ButtomNaviComp",
        key: "Container_drmhamut",
        params: const ButtomNaviCompParams(),
        state: const ButtomNaviCompState(),
        widgets: ButtomNaviCompWidgets.tree,
        paramTypes: <String, ffai.DslType>{
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
      },
    );
  }
}

final class ButtomNaviCompParams {
  const ButtomNaviCompParams();
}

final class ButtomNaviCompState {
  const ButtomNaviCompState();
}

abstract final class ButtomNaviCompWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_drmhamut",
      type: "Container",
      path: "ButtomNaviComp",
      name: "ButtomNaviComp",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Container_el5x4prc",
          type: "Container",
          path: "ButtomNaviComp.children[0]",
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Column_eby7t9i2",
              type: "Column",
              path: "ButtomNaviComp.children[0].children[0]",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Divider_ntwu5i4w",
                  type: "Divider",
                  path: "ButtomNaviComp.children[0].children[0].children[0]",
                ),
                ffai.ProjectWidgetHandle(
                  key: "Row_zep2qqve",
                  type: "Row",
                  path: "ButtomNaviComp.children[0].children[0].children[1]",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "ConditionalBuilder_8dlchyh7",
                      type: "ConditionalBuilder",
                      path: "ButtomNaviComp.children[0].children[0].children[1].children[0]",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "PlaceholderWidget_yr0xlpjq",
                          type: "PlaceholderWidget",
                          path: "ButtomNaviComp.children[0].children[0].children[1].children[0].children[0]",
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Column_7slulxl1",
                              type: "Column",
                              path: "ButtomNaviComp.children[0].children[0].children[1].children[0].children[0].children[0]",
                              triggers: const <String>[
                                "ON_TAP",
                              ],
                              children: <ffai.ProjectWidgetHandle>[
                                ffai.ProjectWidgetHandle(
                                  key: "Icon_1s0jmrah",
                                  type: "Icon",
                                  path: "ButtomNaviComp.children[0].children[0].children[1].children[0].children[0].children[0].children[0]",
                                ),
                                ffai.ProjectWidgetHandle(
                                  key: "Text_9nfs81oo",
                                  type: "Text",
                                  path: "ButtomNaviComp.children[0].children[0].children[1].children[0].children[0].children[0].children[1]",
                                  text: "ホーム",
                                ),
                              ],
                            ),
                          ],
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "PlaceholderWidget_jiofinbj",
                          type: "PlaceholderWidget",
                          path: "ButtomNaviComp.children[0].children[0].children[1].children[0].children[1]",
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Column_lwu19ng7",
                              type: "Column",
                              path: "ButtomNaviComp.children[0].children[0].children[1].children[0].children[1].children[0]",
                              triggers: const <String>[
                                "ON_TAP",
                              ],
                              children: <ffai.ProjectWidgetHandle>[
                                ffai.ProjectWidgetHandle(
                                  key: "Icon_pf4snl8m",
                                  type: "Icon",
                                  path: "ButtomNaviComp.children[0].children[0].children[1].children[0].children[1].children[0].children[0]",
                                ),
                                ffai.ProjectWidgetHandle(
                                  key: "Text_0gx19f2n",
                                  type: "Text",
                                  path: "ButtomNaviComp.children[0].children[0].children[1].children[0].children[1].children[0].children[1]",
                                  text: "ホーム",
                                ),
                              ],
                            ),
                          ],
                        ),
                      ],
                    ),
                    ffai.ProjectWidgetHandle(
                      key: "ConditionalBuilder_5wot902p",
                      type: "ConditionalBuilder",
                      path: "ButtomNaviComp.children[0].children[0].children[1].children[1]",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "PlaceholderWidget_yn9vhno3",
                          type: "PlaceholderWidget",
                          path: "ButtomNaviComp.children[0].children[0].children[1].children[1].children[0]",
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Column_19d7umxz",
                              type: "Column",
                              path: "ButtomNaviComp.children[0].children[0].children[1].children[1].children[0].children[0]",
                              triggers: const <String>[
                                "ON_TAP",
                              ],
                              children: <ffai.ProjectWidgetHandle>[
                                ffai.ProjectWidgetHandle(
                                  key: "Icon_vuhlfs7r",
                                  type: "Icon",
                                  path: "ButtomNaviComp.children[0].children[0].children[1].children[1].children[0].children[0].children[0]",
                                ),
                                ffai.ProjectWidgetHandle(
                                  key: "Text_5ytupzte",
                                  type: "Text",
                                  path: "ButtomNaviComp.children[0].children[0].children[1].children[1].children[0].children[0].children[1]",
                                  text: "ココ店",
                                ),
                              ],
                            ),
                          ],
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "PlaceholderWidget_kaqc2i0p",
                          type: "PlaceholderWidget",
                          path: "ButtomNaviComp.children[0].children[0].children[1].children[1].children[1]",
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Column_96aexmod",
                              type: "Column",
                              path: "ButtomNaviComp.children[0].children[0].children[1].children[1].children[1].children[0]",
                              triggers: const <String>[
                                "ON_TAP",
                              ],
                              children: <ffai.ProjectWidgetHandle>[
                                ffai.ProjectWidgetHandle(
                                  key: "Icon_rh8snqze",
                                  type: "Icon",
                                  path: "ButtomNaviComp.children[0].children[0].children[1].children[1].children[1].children[0].children[0]",
                                ),
                                ffai.ProjectWidgetHandle(
                                  key: "Text_aj816jlc",
                                  type: "Text",
                                  path: "ButtomNaviComp.children[0].children[0].children[1].children[1].children[1].children[0].children[1]",
                                  text: "ココ店",
                                ),
                              ],
                            ),
                          ],
                        ),
                      ],
                    ),
                    ffai.ProjectWidgetHandle(
                      key: "ConditionalBuilder_b1ughq4k",
                      type: "ConditionalBuilder",
                      path: "ButtomNaviComp.children[0].children[0].children[1].children[2]",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "PlaceholderWidget_bqs2pstt",
                          type: "PlaceholderWidget",
                          path: "ButtomNaviComp.children[0].children[0].children[1].children[2].children[0]",
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Column_53mwhc5m",
                              type: "Column",
                              path: "ButtomNaviComp.children[0].children[0].children[1].children[2].children[0].children[0]",
                              triggers: const <String>[
                                "ON_TAP",
                              ],
                              children: <ffai.ProjectWidgetHandle>[
                                ffai.ProjectWidgetHandle(
                                  key: "Icon_j8w6vpq8",
                                  type: "Icon",
                                  path: "ButtomNaviComp.children[0].children[0].children[1].children[2].children[0].children[0].children[0]",
                                ),
                                ffai.ProjectWidgetHandle(
                                  key: "Text_7kjeg0s7",
                                  type: "Text",
                                  path: "ButtomNaviComp.children[0].children[0].children[1].children[2].children[0].children[0].children[1]",
                                  text: "マッチャ",
                                ),
                              ],
                            ),
                          ],
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "PlaceholderWidget_ej4ouyhp",
                          type: "PlaceholderWidget",
                          path: "ButtomNaviComp.children[0].children[0].children[1].children[2].children[1]",
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Column_7ypikfry",
                              type: "Column",
                              path: "ButtomNaviComp.children[0].children[0].children[1].children[2].children[1].children[0]",
                              triggers: const <String>[
                                "ON_TAP",
                              ],
                              children: <ffai.ProjectWidgetHandle>[
                                ffai.ProjectWidgetHandle(
                                  key: "Icon_hdqphu2n",
                                  type: "Icon",
                                  path: "ButtomNaviComp.children[0].children[0].children[1].children[2].children[1].children[0].children[0]",
                                ),
                                ffai.ProjectWidgetHandle(
                                  key: "Text_vaqvdc3q",
                                  type: "Text",
                                  path: "ButtomNaviComp.children[0].children[0].children[1].children[2].children[1].children[0].children[1]",
                                  text: "マッチャ",
                                ),
                              ],
                            ),
                          ],
                        ),
                      ],
                    ),
                    ffai.ProjectWidgetHandle(
                      key: "ConditionalBuilder_kd2vyl2r",
                      type: "ConditionalBuilder",
                      path: "ButtomNaviComp.children[0].children[0].children[1].children[3]",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "PlaceholderWidget_jbazv1s0",
                          type: "PlaceholderWidget",
                          path: "ButtomNaviComp.children[0].children[0].children[1].children[3].children[0]",
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Column_hv9uzr9g",
                              type: "Column",
                              path: "ButtomNaviComp.children[0].children[0].children[1].children[3].children[0].children[0]",
                              triggers: const <String>[
                                "ON_TAP",
                              ],
                              children: <ffai.ProjectWidgetHandle>[
                                ffai.ProjectWidgetHandle(
                                  key: "Icon_j3d6uj29",
                                  type: "Icon",
                                  path: "ButtomNaviComp.children[0].children[0].children[1].children[3].children[0].children[0].children[0]",
                                ),
                                ffai.ProjectWidgetHandle(
                                  key: "Text_fhrbai8d",
                                  type: "Text",
                                  path: "ButtomNaviComp.children[0].children[0].children[1].children[3].children[0].children[0].children[1]",
                                  text: "ワーク",
                                ),
                              ],
                            ),
                          ],
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "PlaceholderWidget_9xwj8u2l",
                          type: "PlaceholderWidget",
                          path: "ButtomNaviComp.children[0].children[0].children[1].children[3].children[1]",
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Column_83rwtkje",
                              type: "Column",
                              path: "ButtomNaviComp.children[0].children[0].children[1].children[3].children[1].children[0]",
                              triggers: const <String>[
                                "ON_TAP",
                              ],
                              children: <ffai.ProjectWidgetHandle>[
                                ffai.ProjectWidgetHandle(
                                  key: "Icon_61ex5xxz",
                                  type: "Icon",
                                  path: "ButtomNaviComp.children[0].children[0].children[1].children[3].children[1].children[0].children[0]",
                                ),
                                ffai.ProjectWidgetHandle(
                                  key: "Text_2fh52pi7",
                                  type: "Text",
                                  path: "ButtomNaviComp.children[0].children[0].children[1].children[3].children[1].children[0].children[1]",
                                  text: "ワーク",
                                ),
                              ],
                            ),
                          ],
                        ),
                      ],
                    ),
                    ffai.ProjectWidgetHandle(
                      key: "ConditionalBuilder_ub60wa2r",
                      type: "ConditionalBuilder",
                      path: "ButtomNaviComp.children[0].children[0].children[1].children[4]",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "PlaceholderWidget_sc80hz43",
                          type: "PlaceholderWidget",
                          path: "ButtomNaviComp.children[0].children[0].children[1].children[4].children[0]",
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Column_8e8b1qjx",
                              type: "Column",
                              path: "ButtomNaviComp.children[0].children[0].children[1].children[4].children[0].children[0]",
                              triggers: const <String>[
                                "ON_TAP",
                              ],
                              children: <ffai.ProjectWidgetHandle>[
                                ffai.ProjectWidgetHandle(
                                  key: "Icon_6fu9335n",
                                  type: "Icon",
                                  path: "ButtomNaviComp.children[0].children[0].children[1].children[4].children[0].children[0].children[0]",
                                ),
                                ffai.ProjectWidgetHandle(
                                  key: "Text_euua5nx9",
                                  type: "Text",
                                  path: "ButtomNaviComp.children[0].children[0].children[1].children[4].children[0].children[0].children[1]",
                                  text: "マイペ",
                                ),
                              ],
                            ),
                          ],
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "PlaceholderWidget_5i2hayju",
                          type: "PlaceholderWidget",
                          path: "ButtomNaviComp.children[0].children[0].children[1].children[4].children[1]",
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Column_k8314hqt",
                              type: "Column",
                              path: "ButtomNaviComp.children[0].children[0].children[1].children[4].children[1].children[0]",
                              triggers: const <String>[
                                "ON_TAP",
                              ],
                              children: <ffai.ProjectWidgetHandle>[
                                ffai.ProjectWidgetHandle(
                                  key: "Icon_vb2a9mx5",
                                  type: "Icon",
                                  path: "ButtomNaviComp.children[0].children[0].children[1].children[4].children[1].children[0].children[0]",
                                ),
                                ffai.ProjectWidgetHandle(
                                  key: "Text_x0o1end7",
                                  type: "Text",
                                  path: "ButtomNaviComp.children[0].children[0].children[1].children[4].children[1].children[0].children[1]",
                                  text: "マイペ",
                                ),
                              ],
                            ),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  );
}

