// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class PrefecturePickerSheetComponentHandle extends ffai.ProjectComponentHandle<PrefecturePickerSheetParams, PrefecturePickerSheetState> {
  PrefecturePickerSheetComponentHandle()
    : super(
        name: "PrefecturePickerSheet",
        key: "Container_67375sp1",
        params: const PrefecturePickerSheetParams(),
        state: const PrefecturePickerSheetState(),
        widgets: PrefecturePickerSheetWidgets.tree,
        paramTypes: <String, ffai.DslType>{
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
      },
    );
  }
}

final class PrefecturePickerSheetParams {
  const PrefecturePickerSheetParams();
}

final class PrefecturePickerSheetState {
  const PrefecturePickerSheetState();
}

abstract final class PrefecturePickerSheetWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_67375sp1",
      type: "Container",
      path: "PrefecturePickerSheet",
      name: "PrefecturePickerSheet",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Container_o7v7mp06",
          type: "Container",
          path: "PrefecturePickerSheet.children[0]",
          name: "Container",
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Column_2oaktk0f",
              type: "Column",
              path: "PrefecturePickerSheet.children[0].children[0]",
              name: "Column",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_9jh2kagb",
                  type: "Text",
                  path: "PrefecturePickerSheet.children[0].children[0].children[0]",
                  name: "Text",
                  text: "都道府県を選択してください",
                ),
                ffai.ProjectWidgetHandle(
                  key: "ListView_tzwj757d",
                  type: "ListView",
                  path: "PrefecturePickerSheet.children[0].children[0].children[1]",
                  name: "ListView",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Button_ufq7tk1o",
                      type: "Button",
                      path: "PrefecturePickerSheet.children[0].children[0].children[1].children[0]",
                      name: "Button",
                      triggers: const <String>[
                        "ON_TAP",
                      ],
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  );
}

