// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class RegistrationPopupCompComponentHandle extends ffai.ProjectComponentHandle<RegistrationPopupCompParams, RegistrationPopupCompState> {
  RegistrationPopupCompComponentHandle()
    : super(
        name: "RegistrationPopupComp",
        key: "Container_upfy08ih",
        params: const RegistrationPopupCompParams(),
        state: const RegistrationPopupCompState(),
        widgets: RegistrationPopupCompWidgets.tree,
        paramTypes: <String, ffai.DslType>{
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
      },
    );
  }
}

final class RegistrationPopupCompParams {
  const RegistrationPopupCompParams();
}

final class RegistrationPopupCompState {
  const RegistrationPopupCompState();
}

abstract final class RegistrationPopupCompWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_upfy08ih",
      type: "Container",
      path: "RegistrationPopupComp",
      name: "RegistrationPopupComp",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Container_2b4kbccg",
          type: "Container",
          path: "RegistrationPopupComp.children[0]",
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Column_nh6iffie",
              type: "Column",
              path: "RegistrationPopupComp.children[0].children[0]",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Image_32ss2me4",
                  type: "Image",
                  path: "RegistrationPopupComp.children[0].children[0].children[0]",
                ),
                ffai.ProjectWidgetHandle(
                  key: "Text_l5agte0o",
                  type: "Text",
                  path: "RegistrationPopupComp.children[0].children[0].children[1]",
                  text: "キャンセル",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Text_s1wbappv",
                  type: "Text",
                  path: "RegistrationPopupComp.children[0].children[0].children[2]",
                  text: "すべての機能やコンテンツを見るには新規登録が必要です。\n引き続きご利用される場合には、お手数をおかけしますが、下記のボタンから新規登録を行ってください。",
                ),
                ffai.ProjectWidgetHandle(
                  key: "Button_agfyg4p7",
                  type: "Button",
                  path: "RegistrationPopupComp.children[0].children[0].children[3]",
                  text: "新規登録に進む",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  );
}

