// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final accountDeletionMonitorPageHandle = ffai.ProjectPageHandle<AccountDeletionMonitorPageParams, AccountDeletionMonitorPageState>(
  name: "AccountDeletionMonitorPage",
  key: "Scaffold_gb0r2x8j",
  route: "admin-deletion-monitor",
  params: const AccountDeletionMonitorPageParams(),
  state: const AccountDeletionMonitorPageState(),
  widgets: AccountDeletionMonitorPageWidgets.tree,
);

final class AccountDeletionMonitorPageParams {
  const AccountDeletionMonitorPageParams();
  ffai.ProjectParamHandle get userId =>
      const ffai.ProjectParamHandle(
        name: "userId",
        key: "ya5r4auj",
        typeName: "String",
      );
  ffai.ProjectParamHandle get userNickname =>
      const ffai.ProjectParamHandle(
        name: "userNickname",
        key: "idezkggi",
        typeName: "String",
      );
}

final class AccountDeletionMonitorPageState {
  const AccountDeletionMonitorPageState();
  ffai.ProjectStateFieldHandle get deletionBlockStatus =>
      const ffai.ProjectStateFieldHandle(
        name: "deletionBlockStatus",
        key: "zeexboi0",
        typeName: "String",
      );
}

abstract final class AccountDeletionMonitorPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_gb0r2x8j",
      type: "Scaffold",
      path: "AccountDeletionMonitorPage",
      name: "AccountDeletionMonitorPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_2xwmzurw",
            type: "AppBar",
            path: "AccountDeletionMonitorPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_pok8s3jr",
                  type: "Text",
                  path: "AccountDeletionMonitorPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "退会ブロック状況",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_9g74nl24",
            type: "Column",
            path: "AccountDeletionMonitorPage.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Text_n98e0vd7",
                type: "Text",
                path: "AccountDeletionMonitorPage.body[0].children[0]",
                name: "Text",
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_jc6gx6j0",
                type: "Text",
                path: "AccountDeletionMonitorPage.body[0].children[1]",
                name: "Text",
              ),
              ffai.ProjectWidgetHandle(
                key: "Divider_ekd477n9",
                type: "Divider",
                path: "AccountDeletionMonitorPage.body[0].children[2]",
                name: "Divider",
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_a932emrz",
                type: "Text",
                path: "AccountDeletionMonitorPage.body[0].children[3]",
                name: "Text",
                text: "手動オーバーライド：ブロック理由の有無に関わらず、このユーザーを強制退会させます。",
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_391ngxre",
                type: "Button",
                path: "AccountDeletionMonitorPage.body[0].children[4]",
                name: "AdminForceDeleteOverrideButton",
                text: "強制退会（ブロックを無視）",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

