// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final activityReportPageHandle = ffai.ProjectPageHandle<ActivityReportPageParams, ActivityReportPageState>(
  name: "ActivityReportPage",
  key: "Scaffold_7plncvsb",
  route: "admin-activity-report",
  params: const ActivityReportPageParams(),
  state: const ActivityReportPageState(),
  widgets: ActivityReportPageWidgets.tree,
);

final class ActivityReportPageParams {
  const ActivityReportPageParams();
}

final class ActivityReportPageState {
  const ActivityReportPageState();
  ffai.ProjectStateFieldHandle get activityReportGranularity =>
      const ffai.ProjectStateFieldHandle(
        name: "activityReportGranularity",
        key: "ij2z8iem",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get activityReportRows =>
      const ffai.ProjectStateFieldHandle(
        name: "activityReportRows",
        key: "yl8dc6j2",
        typeName: "List<String>",
      );
}

abstract final class ActivityReportPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_7plncvsb",
      type: "Scaffold",
      path: "ActivityReportPage",
      name: "ActivityReportPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_imsctebo",
            type: "AppBar",
            path: "ActivityReportPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_6q30mf3w",
                  type: "Text",
                  path: "ActivityReportPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "アクティビティレポート",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_6zz34u2o",
            type: "Column",
            path: "ActivityReportPage.body[0]",
            name: "ActivityReportColumn",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Row_hcnvs308",
                type: "Row",
                path: "ActivityReportPage.body[0].children[0]",
                name: "ActivityReportGranularityRow",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Button_8ssoabfo",
                    type: "Button",
                    path: "ActivityReportPage.body[0].children[0].children[0]",
                    name: "ActivityReportDailyButton",
                    text: "日別（直近30日）",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_3adb6hz6",
                    type: "Button",
                    path: "ActivityReportPage.body[0].children[0].children[1]",
                    name: "ActivityReportMonthlyButton",
                    text: "月別（直近12ヶ月）",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Divider_koi2kt11",
                type: "Divider",
                path: "ActivityReportPage.body[0].children[1]",
                name: "Divider",
              ),
              ffai.ProjectWidgetHandle(
                key: "Row_zsg6qxpz",
                type: "Row",
                path: "ActivityReportPage.body[0].children[2]",
                name: "ActivityReportHeaderRow",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_tsn02q66",
                    type: "Text",
                    path: "ActivityReportPage.body[0].children[2].children[0]",
                    name: "Text",
                    text: "期間",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_zxqdkckd",
                    type: "Text",
                    path: "ActivityReportPage.body[0].children[2].children[1]",
                    name: "Text",
                    text: "新規G",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_651ds16k",
                    type: "Text",
                    path: "ActivityReportPage.body[0].children[2].children[2]",
                    name: "Text",
                    text: "新規C",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_spqj20f8",
                    type: "Text",
                    path: "ActivityReportPage.body[0].children[2].children[3]",
                    name: "Text",
                    text: "予約",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_18j58je3",
                    type: "Text",
                    path: "ActivityReportPage.body[0].children[2].children[4]",
                    name: "Text",
                    text: "完了",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_fj4ia5tc",
                    type: "Text",
                    path: "ActivityReportPage.body[0].children[2].children[5]",
                    name: "Text",
                    text: "取消",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_1vq7xe0n",
                    type: "Text",
                    path: "ActivityReportPage.body[0].children[2].children[6]",
                    name: "Text",
                    text: "売上",
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_eam9cpt4",
                type: "ListView",
                path: "ActivityReportPage.body[0].children[3]",
                name: "ActivityReportListView",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_djy0dfb5",
                    type: "Row",
                    path: "ActivityReportPage.body[0].children[3].children[0]",
                    name: "ActivityReportRowItem",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_cdo2q6tw",
                        type: "Text",
                        path: "ActivityReportPage.body[0].children[3].children[0].children[0]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_nf9ugb1z",
                        type: "Text",
                        path: "ActivityReportPage.body[0].children[3].children[0].children[1]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_4se8bqma",
                        type: "Text",
                        path: "ActivityReportPage.body[0].children[3].children[0].children[2]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_u7rfqceh",
                        type: "Text",
                        path: "ActivityReportPage.body[0].children[3].children[0].children[3]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_ght8xidm",
                        type: "Text",
                        path: "ActivityReportPage.body[0].children[3].children[0].children[4]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_mb6wpq4u",
                        type: "Text",
                        path: "ActivityReportPage.body[0].children[3].children[0].children[5]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_z955k8ac",
                        type: "Text",
                        path: "ActivityReportPage.body[0].children[3].children[0].children[6]",
                        name: "Text",
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Divider_1v7bwq77",
                type: "Divider",
                path: "ActivityReportPage.body[0].children[4]",
                name: "Divider",
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_939evg0u",
                type: "Button",
                path: "ActivityReportPage.body[0].children[5]",
                name: "AdminExportActivityReportCsvButton",
                text: "CSVをコピー（表示中の行）",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

