// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final activityReportPageHandle = ffai.ProjectPageHandle<ActivityReportPageParams, ActivityReportPageState>(
  name: "ActivityReportPage",
  key: "Scaffold_7plncvsb",
  route: "admin-activity-report",
  params: const ActivityReportPageParams(),
  state: const ActivityReportPageState(),
  widgets: ActivityReportPageWidgets.tree,
);

final class ActivityReportPageParams {
  const ActivityReportPageParams();
}

final class ActivityReportPageState {
  const ActivityReportPageState();
  ffai.ProjectStateFieldHandle get activityReportGranularity =>
      const ffai.ProjectStateFieldHandle(
        name: "activityReportGranularity",
        key: "ij2z8iem",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get activityReportRows =>
      const ffai.ProjectStateFieldHandle(
        name: "activityReportRows",
        key: "yl8dc6j2",
        typeName: "List<String>",
      );
}

abstract final class ActivityReportPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_7plncvsb",
      type: "Scaffold",
      path: "ActivityReportPage",
      name: "ActivityReportPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_imsctebo",
            type: "AppBar",
            path: "ActivityReportPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_6q30mf3w",
                  type: "Text",
                  path: "ActivityReportPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "アクティビティレポート",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_ulv6553d",
            type: "Column",
            path: "ActivityReportPage.body[0]",
            name: "ActivityReportColumn",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_kcbrgj7v",
                type: "Container",
                path: "ActivityReportPage.body[0].children[0]",
                name: "ActivityReportAccentBar",
              ),
              ffai.ProjectWidgetHandle(
                key: "Row_g6q3m2wa",
                type: "Row",
                path: "ActivityReportPage.body[0].children[1]",
                name: "ActivityReportGranularityRow",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Button_6lrcre8k",
                    type: "Button",
                    path: "ActivityReportPage.body[0].children[1].children[0]",
                    name: "ActivityReportDailyButton",
                    text: "日別（直近30日）",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_ke4u7orb",
                    type: "Button",
                    path: "ActivityReportPage.body[0].children[1].children[1]",
                    name: "ActivityReportMonthlyButton",
                    text: "月別（直近12ヶ月）",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Divider_hl8rhafj",
                type: "Divider",
                path: "ActivityReportPage.body[0].children[2]",
                name: "Divider",
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_5a5sbcc3",
                type: "Container",
                path: "ActivityReportPage.body[0].children[3]",
                name: "Container",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_wlq4u73j",
                    type: "Row",
                    path: "ActivityReportPage.body[0].children[3].children[0]",
                    name: "ActivityReportHeaderRow",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_c26b38de",
                        type: "Text",
                        path: "ActivityReportPage.body[0].children[3].children[0].children[0]",
                        name: "Text",
                        text: "期間",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_uclzh913",
                        type: "Text",
                        path: "ActivityReportPage.body[0].children[3].children[0].children[1]",
                        name: "Text",
                        text: "新規G",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_40sk9ps5",
                        type: "Text",
                        path: "ActivityReportPage.body[0].children[3].children[0].children[2]",
                        name: "Text",
                        text: "新規C",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_zysr3ysm",
                        type: "Text",
                        path: "ActivityReportPage.body[0].children[3].children[0].children[3]",
                        name: "Text",
                        text: "予約",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_6sa00wa9",
                        type: "Text",
                        path: "ActivityReportPage.body[0].children[3].children[0].children[4]",
                        name: "Text",
                        text: "完了",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_e3rl8eqj",
                        type: "Text",
                        path: "ActivityReportPage.body[0].children[3].children[0].children[5]",
                        name: "Text",
                        text: "取消",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_v44ubcmx",
                        type: "Text",
                        path: "ActivityReportPage.body[0].children[3].children[0].children[6]",
                        name: "Text",
                        text: "売上",
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_b0ryxhye",
                type: "ListView",
                path: "ActivityReportPage.body[0].children[4]",
                name: "ActivityReportListView",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_f1dcnfyz",
                    type: "Row",
                    path: "ActivityReportPage.body[0].children[4].children[0]",
                    name: "ActivityReportRowItem",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_c6vy625r",
                        type: "Text",
                        path: "ActivityReportPage.body[0].children[4].children[0].children[0]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_z05u5ge2",
                        type: "Text",
                        path: "ActivityReportPage.body[0].children[4].children[0].children[1]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_xh38oztl",
                        type: "Text",
                        path: "ActivityReportPage.body[0].children[4].children[0].children[2]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_tkyii7q2",
                        type: "Text",
                        path: "ActivityReportPage.body[0].children[4].children[0].children[3]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_p8ohbcjc",
                        type: "Text",
                        path: "ActivityReportPage.body[0].children[4].children[0].children[4]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_bftdzstm",
                        type: "Text",
                        path: "ActivityReportPage.body[0].children[4].children[0].children[5]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_hz8b9o5v",
                        type: "Text",
                        path: "ActivityReportPage.body[0].children[4].children[0].children[6]",
                        name: "Text",
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Divider_u6j6sot9",
                type: "Divider",
                path: "ActivityReportPage.body[0].children[5]",
                name: "Divider",
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_6sox0vx0",
                type: "Button",
                path: "ActivityReportPage.body[0].children[6]",
                name: "AdminExportActivityReportCsvButton",
                text: "CSVをコピー（表示中の行）",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

