// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final adminReportReviewPageHandle = ffai.ProjectPageHandle<AdminReportReviewPageParams, AdminReportReviewPageState>(
  name: "AdminReportReviewPage",
  key: "Scaffold_711wn4dq",
  route: "admin-report-review",
  params: const AdminReportReviewPageParams(),
  state: const AdminReportReviewPageState(),
  widgets: AdminReportReviewPageWidgets.tree,
);

final class AdminReportReviewPageParams {
  const AdminReportReviewPageParams();
}

final class AdminReportReviewPageState {
  const AdminReportReviewPageState();
  ffai.ProjectStateFieldHandle get adminNote =>
      const ffai.ProjectStateFieldHandle(
        name: "adminNote",
        key: "wvxzzgcf",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get isAdminUser =>
      const ffai.ProjectStateFieldHandle(
        name: "isAdminUser",
        key: "rfr6x0cv",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get pendingReportsList =>
      const ffai.ProjectStateFieldHandle(
        name: "pendingReportsList",
        key: "os300yfs",
        typeName: "List<String>",
      );
  ffai.ProjectStateFieldHandle get selectedReportChatLog =>
      const ffai.ProjectStateFieldHandle(
        name: "selectedReportChatLog",
        key: "n5xa5lkv",
        typeName: "List<String>",
      );
  ffai.ProjectStateFieldHandle get selectedReportId =>
      const ffai.ProjectStateFieldHandle(
        name: "selectedReportId",
        key: "b6gae7od",
        typeName: "String",
      );
}

abstract final class AdminReportReviewPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_711wn4dq",
      type: "Scaffold",
      path: "AdminReportReviewPage",
      name: "AdminReportReviewPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_9jlcq7sj",
            type: "AppBar",
            path: "AdminReportReviewPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_6drt265i",
                  type: "Text",
                  path: "AdminReportReviewPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "通報レビュー",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_28roxe9k",
            type: "Column",
            path: "AdminReportReviewPage.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Text_qjdecfhh",
                type: "Text",
                path: "AdminReportReviewPage.body[0].children[0]",
                name: "Text",
                text: "管理者権限がありません。",
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_ebh3oxlv",
                type: "ListView",
                path: "AdminReportReviewPage.body[0].children[1]",
                name: "PendingReportsListView",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Card_0vahye99",
                    type: "Card",
                    path: "AdminReportReviewPage.body[0].children[1].children[0]",
                    name: "ReportCard",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_ou7mxv4p",
                        type: "Container",
                        path: "AdminReportReviewPage.body[0].children[1].children[0].children[0]",
                        name: "Container",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_bm9va1nj",
                            type: "Column",
                            path: "AdminReportReviewPage.body[0].children[1].children[0].children[0].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_hojlnqqd",
                                type: "Text",
                                path: "AdminReportReviewPage.body[0].children[1].children[0].children[0].children[0].children[0]",
                                name: "Text",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_vc70hk7b",
                                type: "Text",
                                path: "AdminReportReviewPage.body[0].children[1].children[0].children[0].children[0].children[1]",
                                name: "Text",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Button_yh0hp0gw",
                                type: "Button",
                                path: "AdminReportReviewPage.body[0].children[1].children[0].children[0].children[0].children[2]",
                                name: "Button",
                                text: "詳細を見る",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Divider_re3mmftu",
                type: "Divider",
                path: "AdminReportReviewPage.body[0].children[2]",
                name: "Divider",
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_0l0me80z",
                type: "Text",
                path: "AdminReportReviewPage.body[0].children[3]",
                name: "Text",
                text: "チャットログ",
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_zpzxt22z",
                type: "ListView",
                path: "AdminReportReviewPage.body[0].children[4]",
                name: "SelectedReportChatLogListView",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_lmjo622g",
                    type: "Row",
                    path: "AdminReportReviewPage.body[0].children[4].children[0]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_ek7p2s33",
                        type: "Text",
                        path: "AdminReportReviewPage.body[0].children[4].children[0].children[0]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_ua36rae4",
                        type: "Text",
                        path: "AdminReportReviewPage.body[0].children[4].children[0].children[1]",
                        name: "Text",
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_hjsm8avu",
                type: "TextField",
                path: "AdminReportReviewPage.body[0].children[5]",
                name: "AdminNoteField",
                text: "管理者メモ（任意）",
                triggers: const <String>[
                  "ON_TEXTFIELD_CHANGE",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_dzuv9r1c",
                type: "Button",
                path: "AdminReportReviewPage.body[0].children[6]",
                name: "Button",
                text: "解決する",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

