// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final adminAffiliateManagementHandle = ffai.ProjectPageHandle<AdminAffiliateManagementParams, AdminAffiliateManagementState>(
  name: "AdminAffiliateManagement",
  key: "Scaffold_6xwrwobo",
  route: "admin-affiliate-management",
  params: const AdminAffiliateManagementParams(),
  state: const AdminAffiliateManagementState(),
  widgets: AdminAffiliateManagementWidgets.tree,
);

final class AdminAffiliateManagementParams {
  const AdminAffiliateManagementParams();
}

final class AdminAffiliateManagementState {
  const AdminAffiliateManagementState();
  ffai.ProjectStateFieldHandle get affiliatorsList =>
      const ffai.ProjectStateFieldHandle(
        name: "affiliatorsList",
        key: "pvfanoke",
        typeName: "List<String>",
      );
  ffai.ProjectStateFieldHandle get isAdminUser =>
      const ffai.ProjectStateFieldHandle(
        name: "isAdminUser",
        key: "a4ooizlh",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get newRatePercent =>
      const ffai.ProjectStateFieldHandle(
        name: "newRatePercent",
        key: "b8vcvdg7",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get rateHistoryList =>
      const ffai.ProjectStateFieldHandle(
        name: "rateHistoryList",
        key: "ot6ltbab",
        typeName: "List<String>",
      );
  ffai.ProjectStateFieldHandle get selectedNickname =>
      const ffai.ProjectStateFieldHandle(
        name: "selectedNickname",
        key: "e567alrz",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get selectedUid =>
      const ffai.ProjectStateFieldHandle(
        name: "selectedUid",
        key: "j033fu7q",
        typeName: "String",
      );
}

abstract final class AdminAffiliateManagementWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_6xwrwobo",
      type: "Scaffold",
      path: "AdminAffiliateManagement",
      name: "AdminAffiliateManagement",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_h2lyav0f",
            type: "AppBar",
            path: "AdminAffiliateManagement.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_1rgnrlga",
                  type: "Text",
                  path: "AdminAffiliateManagement.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "アフィリエイト管理",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_ar3pwnv7",
            type: "Column",
            path: "AdminAffiliateManagement.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Text_ry1kk8fm",
                type: "Text",
                path: "AdminAffiliateManagement.body[0].children[0]",
                name: "Text",
                text: "管理者権限がありません。",
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_zmo6xgqx",
                type: "ListView",
                path: "AdminAffiliateManagement.body[0].children[1]",
                name: "AffiliatorsListView",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Card_ejullwjy",
                    type: "Card",
                    path: "AdminAffiliateManagement.body[0].children[1].children[0]",
                    name: "AffiliatorCard",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_ehwp9xiy",
                        type: "Container",
                        path: "AdminAffiliateManagement.body[0].children[1].children[0].children[0]",
                        name: "Container",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_arg0hm2w",
                            type: "Column",
                            path: "AdminAffiliateManagement.body[0].children[1].children[0].children[0].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_yhtvq9xp",
                                type: "Text",
                                path: "AdminAffiliateManagement.body[0].children[1].children[0].children[0].children[0].children[0]",
                                name: "Text",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_bbx9u39l",
                                type: "Row",
                                path: "AdminAffiliateManagement.body[0].children[1].children[0].children[0].children[0].children[1]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_29iyy75y",
                                    type: "Text",
                                    path: "AdminAffiliateManagement.body[0].children[1].children[0].children[0].children[0].children[1].children[0]",
                                    name: "Text",
                                    text: "現在の料率：",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_fi60b5r4",
                                    type: "Row",
                                    path: "AdminAffiliateManagement.body[0].children[1].children[0].children[0].children[0].children[1].children[1]",
                                    name: "Row",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_me4di7jw",
                                        type: "Text",
                                        path: "AdminAffiliateManagement.body[0].children[1].children[0].children[0].children[0].children[1].children[1].children[0]",
                                        name: "Text",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_0spwfvnz",
                                        type: "Text",
                                        path: "AdminAffiliateManagement.body[0].children[1].children[0].children[0].children[0].children[1].children[1].children[1]",
                                        name: "Text",
                                        text: "％",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_1588on4w",
                                type: "Row",
                                path: "AdminAffiliateManagement.body[0].children[1].children[0].children[0].children[0].children[2]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_n2ztcv9a",
                                    type: "Text",
                                    path: "AdminAffiliateManagement.body[0].children[1].children[0].children[0].children[0].children[2].children[0]",
                                    name: "Text",
                                    text: "紹介キャスト数：",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_qklgrbph",
                                    type: "Text",
                                    path: "AdminAffiliateManagement.body[0].children[1].children[0].children[0].children[0].children[2].children[1]",
                                    name: "Text",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_lh8kt0ei",
                                type: "Row",
                                path: "AdminAffiliateManagement.body[0].children[1].children[0].children[0].children[0].children[3]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_p3khikq9",
                                    type: "Text",
                                    path: "AdminAffiliateManagement.body[0].children[1].children[0].children[0].children[0].children[3].children[0]",
                                    name: "Text",
                                    text: "累計支払額：",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_ua2wibw8",
                                    type: "Text",
                                    path: "AdminAffiliateManagement.body[0].children[1].children[0].children[0].children[0].children[3].children[1]",
                                    name: "Text",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Button_tpvmrv5c",
                                type: "Button",
                                path: "AdminAffiliateManagement.body[0].children[1].children[0].children[0].children[0].children[4]",
                                name: "Button",
                                text: "選択する",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Divider_0qn1duvy",
                type: "Divider",
                path: "AdminAffiliateManagement.body[0].children[2]",
                name: "Divider",
              ),
              ffai.ProjectWidgetHandle(
                key: "Row_nqj1j2fe",
                type: "Row",
                path: "AdminAffiliateManagement.body[0].children[3]",
                name: "Row",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_37cc4wse",
                    type: "Text",
                    path: "AdminAffiliateManagement.body[0].children[3].children[0]",
                    name: "Text",
                    text: "選択中：",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_u7th0v4w",
                    type: "Text",
                    path: "AdminAffiliateManagement.body[0].children[3].children[1]",
                    name: "Text",
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "DropDown_liv6k8lh",
                type: "DropDown",
                path: "AdminAffiliateManagement.body[0].children[4]",
                name: "Dropdown",
                triggers: const <String>[
                  "ON_FORM_WIDGET_SELECTED",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_el5zbkh5",
                type: "Button",
                path: "AdminAffiliateManagement.body[0].children[5]",
                name: "Button",
                text: "変更する",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_brvt8tfu",
                type: "Text",
                path: "AdminAffiliateManagement.body[0].children[6]",
                name: "Text",
                text: "変更履歴",
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_bwx9i0hy",
                type: "ListView",
                path: "AdminAffiliateManagement.body[0].children[7]",
                name: "RateHistoryListView",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_0hu8aqfe",
                    type: "Row",
                    path: "AdminAffiliateManagement.body[0].children[7].children[0]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_hxwcg549",
                        type: "Text",
                        path: "AdminAffiliateManagement.body[0].children[7].children[0].children[0]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_ssx9chut",
                        type: "Text",
                        path: "AdminAffiliateManagement.body[0].children[7].children[0].children[1]",
                        name: "Text",
                        text: "%  →  ",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_z4vldvcw",
                        type: "Text",
                        path: "AdminAffiliateManagement.body[0].children[7].children[0].children[2]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_gsa34vap",
                        type: "Text",
                        path: "AdminAffiliateManagement.body[0].children[7].children[0].children[3]",
                        name: "Text",
                        text: "%",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_5bq5wzr8",
                        type: "Text",
                        path: "AdminAffiliateManagement.body[0].children[7].children[0].children[4]",
                        name: "Text",
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

