// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final adminDashboardPageHandle = ffai.ProjectPageHandle<AdminDashboardPageParams, AdminDashboardPageState>(
  name: "AdminDashboardPage",
  key: "Scaffold_cum4esme",
  route: "admin-dashboard",
  params: const AdminDashboardPageParams(),
  state: const AdminDashboardPageState(),
  widgets: AdminDashboardPageWidgets.tree,
);

final class AdminDashboardPageParams {
  const AdminDashboardPageParams();
}

final class AdminDashboardPageState {
  const AdminDashboardPageState();
}

abstract final class AdminDashboardPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_cum4esme",
      type: "Scaffold",
      path: "AdminDashboardPage",
      name: "AdminDashboardPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_a6ziyx7k",
            type: "AppBar",
            path: "AdminDashboardPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_juz4to7p",
                  type: "Text",
                  path: "AdminDashboardPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "管理者メニュー",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_meqsixp2",
            type: "Column",
            path: "AdminDashboardPage.body[0]",
            name: "AdminDashboardMenuColumn",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Button_njg4bt2d",
                type: "Button",
                path: "AdminDashboardPage.body[0].children[0]",
                name: "AdminUserManagementNavButton",
                text: "ユーザー管理",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_xbiyppqx",
                type: "Button",
                path: "AdminDashboardPage.body[0].children[1]",
                name: "AdminLedgerOversightNavButton",
                text: "台帳オーバーサイト",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_7po01pvb",
                type: "Button",
                path: "AdminDashboardPage.body[0].children[2]",
                name: "AdminWithdrawalQueueNavButton",
                text: "出金申請キュー",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_45pq0ppm",
                type: "Button",
                path: "AdminDashboardPage.body[0].children[3]",
                name: "AdminWorkPostManagementNavButton",
                text: "ワーク投稿管理",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_p7vu8vc8",
                type: "Button",
                path: "AdminDashboardPage.body[0].children[4]",
                name: "AdminChatOversightNavButton",
                text: "チャットオーバーサイト",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_uxni84ln",
                type: "Button",
                path: "AdminDashboardPage.body[0].children[5]",
                name: "AdminReservationOversightNavButton",
                text: "予約オーバーサイト",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_7yo4kmqd",
                type: "Button",
                path: "AdminDashboardPage.body[0].children[6]",
                name: "AdminKycReviewNavButton",
                text: "KYC審査",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_nvthh13h",
                type: "Button",
                path: "AdminDashboardPage.body[0].children[7]",
                name: "AdminReportReviewNavButton",
                text: "通報レビュー",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_b1kw3vgc",
                type: "Button",
                path: "AdminDashboardPage.body[0].children[8]",
                name: "AdminAffiliateManagementNavButton",
                text: "アフィリエイト管理",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_aul4u419",
                type: "Button",
                path: "AdminDashboardPage.body[0].children[9]",
                name: "AdminNotificationModerationCenterNavButton",
                text: "通知・モデレーションセンター",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_m8t9z6xy",
                type: "Button",
                path: "AdminDashboardPage.body[0].children[10]",
                name: "AdminAuditLogNavButton",
                text: "監査ログ",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_jmp9cy12",
                type: "Button",
                path: "AdminDashboardPage.body[0].children[11]",
                name: "AdminProcessedEventsNavButton",
                text: "ProcessedEvents",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_o9o5dqs7",
                type: "Button",
                path: "AdminDashboardPage.body[0].children[12]",
                name: "AdminBannerManagementNavButton",
                text: "バナー・告知管理",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_oruagrww",
                type: "Button",
                path: "AdminDashboardPage.body[0].children[13]",
                name: "AdminCocotenManagementNavButton",
                text: "CocoTen店舗管理",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_fj6saf7q",
                type: "Button",
                path: "AdminDashboardPage.body[0].children[14]",
                name: "AdminServiceAreaNavButton",
                text: "サービス提供エリア",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_6hx8p8kx",
                type: "Button",
                path: "AdminDashboardPage.body[0].children[15]",
                name: "AdminHomeRankingDiagnosticsNavButton",
                text: "Home表示順診断",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_zbjprhkv",
                type: "Button",
                path: "AdminDashboardPage.body[0].children[16]",
                name: "AdminActivityReportNavButton",
                text: "アクティビティレポート",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

