// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final castProfileHandle = ffai.ProjectPageHandle<CastProfileParams, CastProfileState>(
  name: "CastProfile",
  key: "Scaffold_6r3g5txh",
  route: "",
  params: const CastProfileParams(),
  state: const CastProfileState(),
  widgets: CastProfileWidgets.tree,
);

final class CastProfileParams {
  const CastProfileParams();
}

final class CastProfileState {
  const CastProfileState();
}

abstract final class CastProfileWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_6r3g5txh",
      type: "Scaffold",
      path: "CastProfile",
      name: "CastProfile",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_8xi70k80",
            type: "AppBar",
            path: "CastProfile.appBar[0]",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Row_wxxgjh4u",
                  type: "Row",
                  path: "CastProfile.appBar[0].title[0]",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Row_zwol9hjc",
                      type: "Row",
                      path: "CastProfile.appBar[0].title[0].children[0]",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Icon_s7gxbstb",
                          type: "Icon",
                          path: "CastProfile.appBar[0].title[0].children[0].children[0]",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Image_gnr33ifp",
                          type: "Image",
                          path: "CastProfile.appBar[0].title[0].children[0].children[1]",
                          triggers: const <String>[
                            "ON_TAP",
                          ],
                        ),
                      ],
                    ),
                    ffai.ProjectWidgetHandle(
                      key: "Row_z3kiylot",
                      type: "Row",
                      path: "CastProfile.appBar[0].title[0].children[1]",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Column_m0nx6stc",
                          type: "Column",
                          path: "CastProfile.appBar[0].title[0].children[1].children[0]",
                          triggers: const <String>[
                            "ON_TAP",
                          ],
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Icon_agv3u6ts",
                              type: "Icon",
                              path: "CastProfile.appBar[0].title[0].children[1].children[0].children[0]",
                            ),
                            ffai.ProjectWidgetHandle(
                              key: "Text_n7s3kyeq",
                              type: "Text",
                              path: "CastProfile.appBar[0].title[0].children[1].children[0].children[1]",
                              text: "お知らせ",
                            ),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_w3thqviy",
            type: "Container",
            path: "CastProfile.body[0]",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "ListView_d5buq7eq",
                type: "ListView",
                path: "CastProfile.body[0].children[0]",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_89x6jyks",
                    type: "Column",
                    path: "CastProfile.body[0].children[0].children[0]",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "PageView_lczroe8b",
                        type: "PageView",
                        path: "CastProfile.body[0].children[0].children[0].children[0]",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "PlaceholderWidget_cjuso5lo",
                            type: "PlaceholderWidget",
                            path: "CastProfile.body[0].children[0].children[0].children[0].children[0]",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Stack_ozcjk4h6",
                                type: "Stack",
                                path: "CastProfile.body[0].children[0].children[0].children[0].children[0].children[0]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_09ujd28c",
                                    type: "Column",
                                    path: "CastProfile.body[0].children[0].children[0].children[0].children[0].children[0].children[0]",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Stack_egqvibud",
                                    type: "Stack",
                                    path: "CastProfile.body[0].children[0].children[0].children[0].children[0].children[0].children[1]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Image_1txk54nz",
                                        type: "Image",
                                        path: "CastProfile.body[0].children[0].children[0].children[0].children[0].children[0].children[1].children[0]",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_hvdvwhzj",
                                        type: "Row",
                                        path: "CastProfile.body[0].children[0].children[0].children[0].children[0].children[0].children[1].children[1]",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_6lzm8q15",
                                            type: "Icon",
                                            path: "CastProfile.body[0].children[0].children[0].children[0].children[0].children[0].children[1].children[1].children[0]",
                                            triggers: const <String>[
                                              "ON_TAP",
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_ytvunr3z",
                                            type: "Icon",
                                            path: "CastProfile.body[0].children[0].children[0].children[0].children[0].children[0].children[1].children[1].children[1]",
                                            triggers: const <String>[
                                              "ON_TAP",
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "PlaceholderWidget_rocvqbz8",
                            type: "PlaceholderWidget",
                            path: "CastProfile.body[0].children[0].children[0].children[0].children[1]",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_ismbgirp",
                                type: "Column",
                                path: "CastProfile.body[0].children[0].children[0].children[0].children[1].children[0]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Stack_j63ir700",
                                    type: "Stack",
                                    path: "CastProfile.body[0].children[0].children[0].children[0].children[1].children[0].children[0]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_qbdtwa40",
                                        type: "Row",
                                        path: "CastProfile.body[0].children[0].children[0].children[0].children[1].children[0].children[0].children[0]",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_9yvca3p9",
                                            type: "Icon",
                                            path: "CastProfile.body[0].children[0].children[0].children[0].children[1].children[0].children[0].children[0].children[0]",
                                            triggers: const <String>[
                                              "ON_TAP",
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_t0y2wrdq",
                                            type: "Icon",
                                            path: "CastProfile.body[0].children[0].children[0].children[0].children[1].children[0].children[0].children[0].children[1]",
                                            triggers: const <String>[
                                              "ON_TAP",
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "PlaceholderWidget_qoq99ds7",
                            type: "PlaceholderWidget",
                            path: "CastProfile.body[0].children[0].children[0].children[0].children[2]",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_az5qjyvv",
                                type: "Column",
                                path: "CastProfile.body[0].children[0].children[0].children[0].children[2].children[0]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Stack_elwrubbd",
                                    type: "Stack",
                                    path: "CastProfile.body[0].children[0].children[0].children[0].children[2].children[0].children[0]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_sfvtjqfa",
                                        type: "Row",
                                        path: "CastProfile.body[0].children[0].children[0].children[0].children[2].children[0].children[0].children[0]",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_5ui73czl",
                                            type: "Icon",
                                            path: "CastProfile.body[0].children[0].children[0].children[0].children[2].children[0].children[0].children[0].children[0]",
                                            triggers: const <String>[
                                              "ON_TAP",
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_8a4d1uxj",
                                            type: "Icon",
                                            path: "CastProfile.body[0].children[0].children[0].children[0].children[2].children[0].children[0].children[0].children[1]",
                                            triggers: const <String>[
                                              "ON_TAP",
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "PlaceholderWidget_tyzaiiq8",
                            type: "PlaceholderWidget",
                            path: "CastProfile.body[0].children[0].children[0].children[0].children[3]",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_7u5ehiyi",
                                type: "Column",
                                path: "CastProfile.body[0].children[0].children[0].children[0].children[3].children[0]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Stack_3wtwohqs",
                                    type: "Stack",
                                    path: "CastProfile.body[0].children[0].children[0].children[0].children[3].children[0].children[0]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_30nbbu19",
                                        type: "Row",
                                        path: "CastProfile.body[0].children[0].children[0].children[0].children[3].children[0].children[0].children[0]",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_ebc6gont",
                                            type: "Icon",
                                            path: "CastProfile.body[0].children[0].children[0].children[0].children[3].children[0].children[0].children[0].children[0]",
                                            triggers: const <String>[
                                              "ON_TAP",
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_70wqushr",
                                            type: "Icon",
                                            path: "CastProfile.body[0].children[0].children[0].children[0].children[3].children[0].children[0].children[0].children[1]",
                                            triggers: const <String>[
                                              "ON_TAP",
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "PlaceholderWidget_1vauwe33",
                            type: "PlaceholderWidget",
                            path: "CastProfile.body[0].children[0].children[0].children[0].children[4]",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_yaiz5j2k",
                                type: "Column",
                                path: "CastProfile.body[0].children[0].children[0].children[0].children[4].children[0]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Stack_r5yt0e7a",
                                    type: "Stack",
                                    path: "CastProfile.body[0].children[0].children[0].children[0].children[4].children[0].children[0]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_ghlfinc6",
                                        type: "Row",
                                        path: "CastProfile.body[0].children[0].children[0].children[0].children[4].children[0].children[0].children[0]",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_hz49ekm2",
                                            type: "Icon",
                                            path: "CastProfile.body[0].children[0].children[0].children[0].children[4].children[0].children[0].children[0].children[0]",
                                            triggers: const <String>[
                                              "ON_TAP",
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_5iom82na",
                                            type: "Icon",
                                            path: "CastProfile.body[0].children[0].children[0].children[0].children[4].children[0].children[0].children[0].children[1]",
                                            triggers: const <String>[
                                              "ON_TAP",
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_y7eeny9s",
                        type: "Row",
                        path: "CastProfile.body[0].children[0].children[0].children[1]",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_f3ccxrk5",
                            type: "Text",
                            path: "CastProfile.body[0].children[0].children[0].children[1].children[0]",
                            text: "自己紹介",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_w5pnmiu7",
                        type: "Container",
                        path: "CastProfile.body[0].children[0].children[0].children[2]",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_mm8sgymx",
                            type: "Text",
                            path: "CastProfile.body[0].children[0].children[0].children[2].children[0]",
                            text: "ここに紹介文",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Divider_jmq2ptjf",
                        type: "Divider",
                        path: "CastProfile.body[0].children[0].children[0].children[3]",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_mb1kpqo3",
                        type: "Row",
                        path: "CastProfile.body[0].children[0].children[0].children[4]",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_snz4hqcj",
                            type: "Button",
                            path: "CastProfile.body[0].children[0].children[0].children[4].children[0]",
                            text: "誘　う",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Button_z76lh1eh",
                            type: "Button",
                            path: "CastProfile.body[0].children[0].children[0].children[4].children[1]",
                            text: "ココ店で誘う",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Divider_1z80jpyb",
                        type: "Divider",
                        path: "CastProfile.body[0].children[0].children[0].children[5]",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_vk811dsc",
                        type: "Container",
                        path: "CastProfile.body[0].children[0].children[0].children[6]",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Stack_zgon3qg2",
                            type: "Stack",
                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0]",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "TabBar_dwmb52e6",
                                type: "TabBar",
                                path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Tab_i05ewg34",
                                    type: "Tab",
                                    path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[0]",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "PlaceholderWidget_2hio7zs0",
                                    type: "PlaceholderWidget",
                                    path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_k6iwmcd7",
                                        type: "Container",
                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0]",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Column_ta4sgzak",
                                            type: "Column",
                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0]",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Row_frq1v04n",
                                                type: "Row",
                                                path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0]",
                                                children: <ffai.ProjectWidgetHandle>[
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Row_fnd5odwo",
                                                    type: "Row",
                                                    path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[0]",
                                                    children: <ffai.ProjectWidgetHandle>[
                                                      ffai.ProjectWidgetHandle(
                                                        key: "Column_ok55e4io",
                                                        type: "Column",
                                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[0].children[0]",
                                                        children: <ffai.ProjectWidgetHandle>[
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_gd3rv6f1",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[0].children[0].children[0]",
                                                            text: "ニクネ",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_3pwk0ern",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[0].children[0].children[1]",
                                                            text: "性　別",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_otrzpqsx",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[0].children[0].children[2]",
                                                            text: "飲　酒",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_3350unac",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[0].children[0].children[3]",
                                                            text: "趣　味",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_ms8cilt4",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[0].children[0].children[4]",
                                                            text: "職　業",
                                                          ),
                                                        ],
                                                      ),
                                                      ffai.ProjectWidgetHandle(
                                                        key: "Column_ci08gtwt",
                                                        type: "Column",
                                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[0].children[1]",
                                                        children: <ffai.ProjectWidgetHandle>[
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_paocpcw9",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[0].children[1].children[0]",
                                                            text: "：",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_wlv9fcmm",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[0].children[1].children[1]",
                                                            text: "：",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_lrtw53q6",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[0].children[1].children[2]",
                                                            text: "：",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_tbeck0ox",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[0].children[1].children[3]",
                                                            text: "：",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_p0lzpggv",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[0].children[1].children[4]",
                                                            text: "：",
                                                          ),
                                                        ],
                                                      ),
                                                      ffai.ProjectWidgetHandle(
                                                        key: "Column_8k3raj4k",
                                                        type: "Column",
                                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[0].children[2]",
                                                        children: <ffai.ProjectWidgetHandle>[
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_trtwcirr",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[0].children[2].children[0]",
                                                            text: "ゆずき",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_7v7rb8lv",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[0].children[2].children[1]",
                                                            text: "女　性",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_2a74lhe3",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[0].children[2].children[2]",
                                                            text: "少し飲む",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_mu79rkv5",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[0].children[2].children[3]",
                                                            text: "ドライブ",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_kqvtp68t",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[0].children[2].children[4]",
                                                            text: "ネイリスト",
                                                          ),
                                                        ],
                                                      ),
                                                    ],
                                                  ),
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Row_svwkx16u",
                                                    type: "Row",
                                                    path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[1]",
                                                    children: <ffai.ProjectWidgetHandle>[
                                                      ffai.ProjectWidgetHandle(
                                                        key: "Column_or136nh4",
                                                        type: "Column",
                                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[1].children[0]",
                                                        children: <ffai.ProjectWidgetHandle>[
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_rqbgt5ov",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[1].children[0].children[0]",
                                                            text: "地　域",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_vvkx2an6",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[1].children[0].children[1]",
                                                            text: "年齢層",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_tpouin29",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[1].children[0].children[2]",
                                                            text: "喫　煙",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_rog3p5h7",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[1].children[0].children[3]",
                                                            text: "特　技",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_74agkbc9",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[1].children[0].children[4]",
                                                            text: "好き食",
                                                          ),
                                                        ],
                                                      ),
                                                      ffai.ProjectWidgetHandle(
                                                        key: "Column_9e3tmdel",
                                                        type: "Column",
                                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[1].children[1]",
                                                        children: <ffai.ProjectWidgetHandle>[
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_ho8yg78b",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[1].children[1].children[0]",
                                                            text: "：",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_clxu7ceh",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[1].children[1].children[1]",
                                                            text: "：",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_co1s6feh",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[1].children[1].children[2]",
                                                            text: "：",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_av3d8cuv",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[1].children[1].children[3]",
                                                            text: "：",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_z4jmbq9k",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[1].children[1].children[4]",
                                                            text: "：",
                                                          ),
                                                        ],
                                                      ),
                                                      ffai.ProjectWidgetHandle(
                                                        key: "Column_lkoey0dl",
                                                        type: "Column",
                                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[1].children[2]",
                                                        children: <ffai.ProjectWidgetHandle>[
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_0iu7le38",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[1].children[2].children[0]",
                                                            text: "東京都 港区",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_d21l7w8l",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[1].children[2].children[1]",
                                                            text: "20 歳代 後半",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_fser96d6",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[1].children[2].children[2]",
                                                            text: "吸わない",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_nx8vigvf",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[1].children[2].children[3]",
                                                            text: "寝ること",
                                                          ),
                                                          ffai.ProjectWidgetHandle(
                                                            key: "Text_fk2r1yvf",
                                                            type: "Text",
                                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0].children[1].children[2].children[4]",
                                                            text: "焼　肉",
                                                          ),
                                                        ],
                                                      ),
                                                    ],
                                                  ),
                                                ],
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Tab_wnnhsod4",
                                    type: "Tab",
                                    path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[2]",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "PlaceholderWidget_mfks4kgs",
                                    type: "PlaceholderWidget",
                                    path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_j0utxnek",
                                        type: "Container",
                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0]",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Column_2zgvbyae",
                                            type: "Column",
                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0]",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Row_7w84o5jk",
                                                type: "Row",
                                                path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[0]",
                                                children: <ffai.ProjectWidgetHandle>[
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Container_crfkya8f",
                                                    type: "Container",
                                                    path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[0].children[0]",
                                                    children: <ffai.ProjectWidgetHandle>[
                                                      ffai.ProjectWidgetHandle(
                                                        key: "Image_1lce00ek",
                                                        type: "Image",
                                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[0].children[0].children[0]",
                                                      ),
                                                    ],
                                                  ),
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Container_btku0qu6",
                                                    type: "Container",
                                                    path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[0].children[1]",
                                                    children: <ffai.ProjectWidgetHandle>[
                                                      ffai.ProjectWidgetHandle(
                                                        key: "Image_ibys61ot",
                                                        type: "Image",
                                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[0].children[1].children[0]",
                                                      ),
                                                    ],
                                                  ),
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Container_7oxat7n3",
                                                    type: "Container",
                                                    path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[0].children[2]",
                                                    children: <ffai.ProjectWidgetHandle>[
                                                      ffai.ProjectWidgetHandle(
                                                        key: "Image_7nk13uzb",
                                                        type: "Image",
                                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[0].children[2].children[0]",
                                                      ),
                                                    ],
                                                  ),
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Container_7h2lu94h",
                                                    type: "Container",
                                                    path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[0].children[3]",
                                                    children: <ffai.ProjectWidgetHandle>[
                                                      ffai.ProjectWidgetHandle(
                                                        key: "Image_3gwb0mzj",
                                                        type: "Image",
                                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[0].children[3].children[0]",
                                                      ),
                                                    ],
                                                  ),
                                                ],
                                              ),
                                              ffai.ProjectWidgetHandle(
                                                key: "Row_v4lfqt2c",
                                                type: "Row",
                                                path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[1]",
                                                children: <ffai.ProjectWidgetHandle>[
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Container_5b9hmk3w",
                                                    type: "Container",
                                                    path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[1].children[0]",
                                                    children: <ffai.ProjectWidgetHandle>[
                                                      ffai.ProjectWidgetHandle(
                                                        key: "Image_xpljdj1c",
                                                        type: "Image",
                                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[1].children[0].children[0]",
                                                      ),
                                                    ],
                                                  ),
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Container_3l5kftar",
                                                    type: "Container",
                                                    path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[1].children[1]",
                                                    children: <ffai.ProjectWidgetHandle>[
                                                      ffai.ProjectWidgetHandle(
                                                        key: "Image_wxbolziw",
                                                        type: "Image",
                                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[1].children[1].children[0]",
                                                      ),
                                                    ],
                                                  ),
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Container_5l25952h",
                                                    type: "Container",
                                                    path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[1].children[2]",
                                                    children: <ffai.ProjectWidgetHandle>[
                                                      ffai.ProjectWidgetHandle(
                                                        key: "Image_nin5wgz1",
                                                        type: "Image",
                                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[1].children[2].children[0]",
                                                      ),
                                                    ],
                                                  ),
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Container_ou491pl6",
                                                    type: "Container",
                                                    path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[1].children[3]",
                                                    children: <ffai.ProjectWidgetHandle>[
                                                      ffai.ProjectWidgetHandle(
                                                        key: "Image_268locql",
                                                        type: "Image",
                                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[1].children[3].children[0]",
                                                      ),
                                                    ],
                                                  ),
                                                ],
                                              ),
                                              ffai.ProjectWidgetHandle(
                                                key: "Row_gg7ey9fx",
                                                type: "Row",
                                                path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[2]",
                                                children: <ffai.ProjectWidgetHandle>[
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Container_wmadjibe",
                                                    type: "Container",
                                                    path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[2].children[0]",
                                                    children: <ffai.ProjectWidgetHandle>[
                                                      ffai.ProjectWidgetHandle(
                                                        key: "Image_kjlcp6oc",
                                                        type: "Image",
                                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[2].children[0].children[0]",
                                                      ),
                                                    ],
                                                  ),
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Container_h4o072fo",
                                                    type: "Container",
                                                    path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[2].children[1]",
                                                    children: <ffai.ProjectWidgetHandle>[
                                                      ffai.ProjectWidgetHandle(
                                                        key: "Image_1oi52wfm",
                                                        type: "Image",
                                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[2].children[1].children[0]",
                                                      ),
                                                    ],
                                                  ),
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Container_u0jr9zvy",
                                                    type: "Container",
                                                    path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[2].children[2]",
                                                    children: <ffai.ProjectWidgetHandle>[
                                                      ffai.ProjectWidgetHandle(
                                                        key: "Image_543xfkwd",
                                                        type: "Image",
                                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[2].children[2].children[0]",
                                                      ),
                                                    ],
                                                  ),
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Container_u4c6db40",
                                                    type: "Container",
                                                    path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[2].children[3]",
                                                    children: <ffai.ProjectWidgetHandle>[
                                                      ffai.ProjectWidgetHandle(
                                                        key: "Image_wl4lgpq7",
                                                        type: "Image",
                                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[3].children[0].children[0].children[2].children[3].children[0]",
                                                      ),
                                                    ],
                                                  ),
                                                ],
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Tab_e4xzahj2",
                                    type: "Tab",
                                    path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[4]",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "PlaceholderWidget_khyoom7e",
                                    type: "PlaceholderWidget",
                                    path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[5]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_rhq0mgev",
                                        type: "Container",
                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[5].children[0]",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Column_u85nrwwf",
                                            type: "Column",
                                            path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[5].children[0].children[0]",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Calendar_pgw6bzqc",
                                                type: "Calendar",
                                                path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[0].children[5].children[0].children[0].children[0]",
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_efcf895f",
                                type: "Row",
                                path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[1]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_mf51d816",
                                    type: "Column",
                                    path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[1].children[0]",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_p1b1wwzs",
                                        type: "Icon",
                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[1].children[0].children[0]",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_5mr1x6pl",
                                        type: "Text",
                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[1].children[0].children[1]",
                                        text: "プロフ",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_6hz43qu0",
                                    type: "Column",
                                    path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[1].children[1]",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_0rr4tbvk",
                                        type: "Icon",
                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[1].children[1].children[0]",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_r2mq46su",
                                        type: "Text",
                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[1].children[1].children[1]",
                                        text: "フォト",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_zg2c31n6",
                                    type: "Column",
                                    path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[1].children[2]",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_aiyljumb",
                                        type: "Icon",
                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[1].children[2].children[0]",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_zjy6qzvc",
                                        type: "Text",
                                        path: "CastProfile.body[0].children[0].children[0].children[6].children[0].children[1].children[2].children[1]",
                                        text: "予定表",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

