// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final cocomisePageHandle = ffai.ProjectPageHandle<CocomisePageParams, CocomisePageState>(
  name: "CocomisePage",
  key: "Scaffold_93t65r3u",
  route: "",
  params: const CocomisePageParams(),
  state: const CocomisePageState(),
  widgets: CocomisePageWidgets.tree,
);

final class CocomisePageParams {
  const CocomisePageParams();
}

final class CocomisePageState {
  const CocomisePageState();
  ffai.ProjectStateFieldHandle get activeOnly =>
      const ffai.ProjectStateFieldHandle(
        name: "activeOnly",
        key: "vzd5cenz",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get prefectureOptions =>
      const ffai.ProjectStateFieldHandle(
        name: "prefectureOptions",
        key: "tyfn6nb8",
        typeName: "List<String>",
      );
  ffai.ProjectStateFieldHandle get selectedGenre =>
      const ffai.ProjectStateFieldHandle(
        name: "selectedGenre",
        key: "judxim3o",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get selectedPrefecture =>
      const ffai.ProjectStateFieldHandle(
        name: "selectedPrefecture",
        key: "szptz9ql",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get shops =>
      const ffai.ProjectStateFieldHandle(
        name: "shops",
        key: "26kw6tfu",
        typeName: "List<Document<cocoten_shops>>",
      );
}

abstract final class CocomisePageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_93t65r3u",
      type: "Scaffold",
      path: "CocomisePage",
      name: "CocomisePage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_mlq5yonq",
            type: "AppBar",
            path: "CocomisePage.appBar[0]",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Row_0k2f660o",
                  type: "Row",
                  path: "CocomisePage.appBar[0].title[0]",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Image_8kcwkbva",
                      type: "Image",
                      path: "CocomisePage.appBar[0].title[0].children[0]",
                      triggers: const <String>[
                        "ON_TAP",
                      ],
                    ),
                    ffai.ProjectWidgetHandle(
                      key: "Row_ut7sspa3",
                      type: "Row",
                      path: "CocomisePage.appBar[0].title[0].children[1]",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Column_tom1mqyd",
                          type: "Column",
                          path: "CocomisePage.appBar[0].title[0].children[1].children[0]",
                          triggers: const <String>[
                            "ON_TAP",
                          ],
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Icon_nu6zaozz",
                              type: "Icon",
                              path: "CocomisePage.appBar[0].title[0].children[1].children[0].children[0]",
                            ),
                            ffai.ProjectWidgetHandle(
                              key: "Text_v3cpvda5",
                              type: "Text",
                              path: "CocomisePage.appBar[0].title[0].children[1].children[0].children[1]",
                              text: "検 索",
                            ),
                          ],
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Column_6qbfkgti",
                          type: "Column",
                          path: "CocomisePage.appBar[0].title[0].children[1].children[1]",
                          triggers: const <String>[
                            "ON_TAP",
                          ],
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Icon_lo5l6vtk",
                              type: "Icon",
                              path: "CocomisePage.appBar[0].title[0].children[1].children[1].children[0]",
                            ),
                            ffai.ProjectWidgetHandle(
                              key: "Text_hqtbhuav",
                              type: "Text",
                              path: "CocomisePage.appBar[0].title[0].children[1].children[1].children[1]",
                              text: "お知らせ",
                            ),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Stack_t81x7dog",
            type: "Stack",
            path: "CocomisePage.body[0]",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_l4fd7zus",
                type: "Container",
                path: "CocomisePage.body[0].children[0]",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "ListView_tri8rxdu",
                    type: "ListView",
                    path: "CocomisePage.body[0].children[0].children[0]",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_eqef1t0l",
                        type: "Column",
                        path: "CocomisePage.body[0].children[0].children[0].children[0]",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_7ppaumnu",
                            type: "Container",
                            path: "CocomisePage.body[0].children[0].children[0].children[0].children[0]",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "PageView_ea9ah9kd",
                                type: "PageView",
                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "PlaceholderWidget_io2z73z5",
                                    type: "PlaceholderWidget",
                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[0]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_5riczx1s",
                                        type: "Column",
                                        path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[0].children[0]",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Stack_phlpmre3",
                                            type: "Stack",
                                            path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[0].children[0].children[0]",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Image_dkzvgwre",
                                                type: "Image",
                                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[0].children[0].children[0].children[0]",
                                              ),
                                              ffai.ProjectWidgetHandle(
                                                key: "Row_8kw07g04",
                                                type: "Row",
                                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[0].children[0].children[0].children[1]",
                                                children: <ffai.ProjectWidgetHandle>[
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Icon_0ijygmr6",
                                                    type: "Icon",
                                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[0].children[0].children[0].children[1].children[0]",
                                                    triggers: const <String>[
                                                      "ON_TAP",
                                                    ],
                                                  ),
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Icon_86xr5p0q",
                                                    type: "Icon",
                                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[0].children[0].children[0].children[1].children[1]",
                                                    triggers: const <String>[
                                                      "ON_TAP",
                                                    ],
                                                  ),
                                                ],
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "PlaceholderWidget_3p3ei5dr",
                                    type: "PlaceholderWidget",
                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[1]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_qlyemgdq",
                                        type: "Column",
                                        path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[1].children[0]",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Stack_ur5zrhf7",
                                            type: "Stack",
                                            path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[1].children[0].children[0]",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Image_aoopy7b4",
                                                type: "Image",
                                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[1].children[0].children[0].children[0]",
                                              ),
                                              ffai.ProjectWidgetHandle(
                                                key: "Row_a0z2ys68",
                                                type: "Row",
                                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[1].children[0].children[0].children[1]",
                                                children: <ffai.ProjectWidgetHandle>[
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Icon_jnnza33b",
                                                    type: "Icon",
                                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[1].children[0].children[0].children[1].children[0]",
                                                    triggers: const <String>[
                                                      "ON_TAP",
                                                    ],
                                                  ),
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Icon_a6z0h7yl",
                                                    type: "Icon",
                                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[1].children[0].children[0].children[1].children[1]",
                                                    triggers: const <String>[
                                                      "ON_TAP",
                                                    ],
                                                  ),
                                                ],
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "PlaceholderWidget_da5pyp98",
                                    type: "PlaceholderWidget",
                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[2]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_r9qmyx5q",
                                        type: "Column",
                                        path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[2].children[0]",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Stack_le2mwref",
                                            type: "Stack",
                                            path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[2].children[0].children[0]",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Image_hideg0h1",
                                                type: "Image",
                                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[2].children[0].children[0].children[0]",
                                              ),
                                              ffai.ProjectWidgetHandle(
                                                key: "Row_pgxa5l1t",
                                                type: "Row",
                                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[2].children[0].children[0].children[1]",
                                                children: <ffai.ProjectWidgetHandle>[
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Icon_r6k4isdf",
                                                    type: "Icon",
                                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[2].children[0].children[0].children[1].children[0]",
                                                    triggers: const <String>[
                                                      "ON_TAP",
                                                    ],
                                                  ),
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Icon_ckrkv55l",
                                                    type: "Icon",
                                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[2].children[0].children[0].children[1].children[1]",
                                                    triggers: const <String>[
                                                      "ON_TAP",
                                                    ],
                                                  ),
                                                ],
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "PlaceholderWidget_kl4tf1jc",
                                    type: "PlaceholderWidget",
                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[3]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_sg2dmtoe",
                                        type: "Column",
                                        path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[3].children[0]",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Stack_ivdtctr2",
                                            type: "Stack",
                                            path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[3].children[0].children[0]",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Image_9q3sv9ot",
                                                type: "Image",
                                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[3].children[0].children[0].children[0]",
                                              ),
                                              ffai.ProjectWidgetHandle(
                                                key: "Row_2vc8goe6",
                                                type: "Row",
                                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[3].children[0].children[0].children[1]",
                                                children: <ffai.ProjectWidgetHandle>[
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Icon_1f0u304x",
                                                    type: "Icon",
                                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[3].children[0].children[0].children[1].children[0]",
                                                    triggers: const <String>[
                                                      "ON_TAP",
                                                    ],
                                                  ),
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Icon_b52688vi",
                                                    type: "Icon",
                                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[3].children[0].children[0].children[1].children[1]",
                                                    triggers: const <String>[
                                                      "ON_TAP",
                                                    ],
                                                  ),
                                                ],
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "PlaceholderWidget_7jmod7ms",
                                    type: "PlaceholderWidget",
                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[4]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_eonwxkoa",
                                        type: "Column",
                                        path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[4].children[0]",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Stack_94pv8efy",
                                            type: "Stack",
                                            path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[4].children[0].children[0]",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Image_tispo3jj",
                                                type: "Image",
                                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[4].children[0].children[0].children[0]",
                                              ),
                                              ffai.ProjectWidgetHandle(
                                                key: "Row_cwh7yya5",
                                                type: "Row",
                                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[4].children[0].children[0].children[1]",
                                                children: <ffai.ProjectWidgetHandle>[
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Icon_cos9bf8t",
                                                    type: "Icon",
                                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[4].children[0].children[0].children[1].children[0]",
                                                    triggers: const <String>[
                                                      "ON_TAP",
                                                    ],
                                                  ),
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Icon_lyeojd1z",
                                                    type: "Icon",
                                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[0].children[0].children[4].children[0].children[0].children[1].children[1]",
                                                    triggers: const <String>[
                                                      "ON_TAP",
                                                    ],
                                                  ),
                                                ],
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Divider_k4s60x59",
                            type: "Divider",
                            path: "CocomisePage.body[0].children[0].children[0].children[0].children[1]",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Row_8yyew9l5",
                            type: "Row",
                            path: "CocomisePage.body[0].children[0].children[0].children[0].children[2]",
                            name: "CocomiseOpenOnlyRow",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_a7qh1c04",
                                type: "Column",
                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[2].children[0]",
                                name: "Column",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_bdh6maz2",
                                    type: "Text",
                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[2].children[0].children[0]",
                                    name: "Text",
                                    text: "オープン",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_o7envbep",
                                    type: "Text",
                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[2].children[0].children[1]",
                                    name: "Text",
                                    text: "開店中のお店表示",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Checkbox_uxda3bmb",
                                type: "Checkbox",
                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[2].children[1]",
                                name: "CocomiseOpenOnlyCheckbox",
                                triggers: const <String>[
                                  "ON_TOGGLE_ON",
                                  "ON_TOGGLE_OFF",
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Divider_0vbhp74d",
                            type: "Divider",
                            path: "CocomisePage.body[0].children[0].children[0].children[0].children[3]",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Row_mylw52qj",
                            type: "Row",
                            path: "CocomisePage.body[0].children[0].children[0].children[0].children[4]",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_0wh21mpc",
                                type: "Container",
                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[4].children[0]",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_s8djrtcv",
                                    type: "Text",
                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[4].children[0].children[0]",
                                    text: "和　食",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_woiyd378",
                                type: "Container",
                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[4].children[1]",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_owam0vxv",
                                    type: "Text",
                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[4].children[1].children[0]",
                                    text: "洋　食",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_i8nod4uz",
                                type: "Container",
                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[4].children[2]",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_mxfma42p",
                                    type: "Text",
                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[4].children[2].children[0]",
                                    text: "和洋食",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_z0t09uyq",
                                type: "Container",
                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[4].children[3]",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_s56uttsr",
                                    type: "Text",
                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[4].children[3].children[0]",
                                    text: "イタ飯",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_40qrlyom",
                                type: "Container",
                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[4].children[4]",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_a7yt3dgw",
                                    type: "Text",
                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[4].children[4].children[0]",
                                    text: "韓　食",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_09intull",
                                type: "Container",
                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[4].children[5]",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_6mtzaw9e",
                                    type: "Text",
                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[4].children[5].children[0]",
                                    text: "中　華",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_2wq3wtxf",
                                type: "Container",
                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[4].children[6]",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_65tbdor3",
                                    type: "Text",
                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[4].children[6].children[0]",
                                    text: "その他",
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_h5w7ijp6",
                            type: "Container",
                            path: "CocomisePage.body[0].children[0].children[0].children[0].children[5]",
                            name: "CocotenPrefectureFilterRow",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "ListView_5ymgtqrt",
                                type: "ListView",
                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[5].children[0]",
                                name: "CocotenPrefectureFilterList",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_mrn5k5pf",
                                    type: "Container",
                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[5].children[0].children[0]",
                                    name: "Container",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_fifq9jt4",
                                        type: "Text",
                                        path: "CocomisePage.body[0].children[0].children[0].children[0].children[5].children[0].children[0].children[0]",
                                        name: "Text",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Divider_svkd9ckr",
                            type: "Divider",
                            path: "CocomisePage.body[0].children[0].children[0].children[0].children[6]",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_s97aye5a",
                            type: "Container",
                            path: "CocomisePage.body[0].children[0].children[0].children[0].children[7]",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "GridView_uuxxt020",
                                type: "GridView",
                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[7].children[0]",
                                name: "CocotenShopGrid",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_pbbsgfev",
                                    type: "Container",
                                    path: "CocomisePage.body[0].children[0].children[0].children[0].children[7].children[0].children[0]",
                                    name: "CocotenShopCard",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_xe7lyqo0",
                                        type: "Column",
                                        path: "CocomisePage.body[0].children[0].children[0].children[0].children[7].children[0].children[0].children[0]",
                                        name: "Column",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Row_hmsnobq5",
                                            type: "Row",
                                            path: "CocomisePage.body[0].children[0].children[0].children[0].children[7].children[0].children[0].children[0].children[0]",
                                            name: "Row",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_p9o9j2o9",
                                                type: "Text",
                                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[7].children[0].children[0].children[0].children[0].children[0]",
                                                name: "Text",
                                              ),
                                              ffai.ProjectWidgetHandle(
                                                key: "Container_ruikeqre",
                                                type: "Container",
                                                path: "CocomisePage.body[0].children[0].children[0].children[0].children[7].children[0].children[0].children[0].children[0].children[1]",
                                                name: "CocotenShopActiveDot",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_td3inop5",
                                            type: "Text",
                                            path: "CocomisePage.body[0].children[0].children[0].children[0].children[7].children[0].children[0].children[0].children[1]",
                                            name: "Text",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_3qtgbt7n",
                type: "Container",
                path: "CocomisePage.body[0].children[1]",
                componentName: "ButtomNaviComp",
              ),
            ],
          ),
        ],
      },
    ),
  );
}

