// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final cocoTenDetailPageHandle = ffai.ProjectPageHandle<CocoTenDetailPageParams, CocoTenDetailPageState>(
  name: "CocoTenDetailPage",
  key: "Scaffold_ewew5iot",
  route: "cocoten-detail",
  params: const CocoTenDetailPageParams(),
  state: const CocoTenDetailPageState(),
  widgets: CocoTenDetailPageWidgets.tree,
);

final class CocoTenDetailPageParams {
  const CocoTenDetailPageParams();
  ffai.ProjectParamHandle get shopActive =>
      const ffai.ProjectParamHandle(
        name: "shopActive",
        key: "lqghh8nq",
        typeName: "Boolean",
      );
  ffai.ProjectParamHandle get shopAddress =>
      const ffai.ProjectParamHandle(
        name: "shopAddress",
        key: "gjhktm1l",
        typeName: "String",
      );
  ffai.ProjectParamHandle get shopGenre =>
      const ffai.ProjectParamHandle(
        name: "shopGenre",
        key: "o7uw62lx",
        typeName: "String",
      );
  ffai.ProjectParamHandle get shopGuestBenefits =>
      const ffai.ProjectParamHandle(
        name: "shopGuestBenefits",
        key: "oaoyonx9",
        typeName: "String",
      );
  ffai.ProjectParamHandle get shopId =>
      const ffai.ProjectParamHandle(
        name: "shopId",
        key: "8uv0fg5z",
        typeName: "String",
      );
  ffai.ProjectParamHandle get shopMenu =>
      const ffai.ProjectParamHandle(
        name: "shopMenu",
        key: "1cbxi7y3",
        typeName: "String",
      );
  ffai.ProjectParamHandle get shopName =>
      const ffai.ProjectParamHandle(
        name: "shopName",
        key: "d3njptam",
        typeName: "String",
      );
}

final class CocoTenDetailPageState {
  const CocoTenDetailPageState();
  ffai.ProjectStateFieldHandle get shopActiveState =>
      const ffai.ProjectStateFieldHandle(
        name: "shopActiveState",
        key: "le5e1m0q",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get shopAddressState =>
      const ffai.ProjectStateFieldHandle(
        name: "shopAddressState",
        key: "q2mixxqe",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get shopGenreState =>
      const ffai.ProjectStateFieldHandle(
        name: "shopGenreState",
        key: "owic6bvm",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get shopGuestBenefitsState =>
      const ffai.ProjectStateFieldHandle(
        name: "shopGuestBenefitsState",
        key: "gcdfd0te",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get shopMenuState =>
      const ffai.ProjectStateFieldHandle(
        name: "shopMenuState",
        key: "y35n2ikb",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get shopNameState =>
      const ffai.ProjectStateFieldHandle(
        name: "shopNameState",
        key: "0ssiyrpo",
        typeName: "String",
      );
}

abstract final class CocoTenDetailPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_ewew5iot",
      type: "Scaffold",
      path: "CocoTenDetailPage",
      name: "CocoTenDetailPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_2wgargij",
            type: "AppBar",
            path: "CocoTenDetailPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_iwcsnddi",
                  type: "Text",
                  path: "CocoTenDetailPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "ココ店詳細",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_vcbvxrzv",
            type: "Column",
            path: "CocoTenDetailPage.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Row_yaocs611",
                type: "Row",
                path: "CocoTenDetailPage.body[0].children[0]",
                name: "Row",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_wixghz8n",
                    type: "Text",
                    path: "CocoTenDetailPage.body[0].children[0].children[0]",
                    name: "Text",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_u3d8f82o",
                    type: "Container",
                    path: "CocoTenDetailPage.body[0].children[0].children[1]",
                    name: "CocoTenDetailActiveDot",
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_9jzm4w9b",
                type: "Text",
                path: "CocoTenDetailPage.body[0].children[1]",
                name: "Text",
              ),
              ffai.ProjectWidgetHandle(
                key: "Divider_uny39lip",
                type: "Divider",
                path: "CocoTenDetailPage.body[0].children[2]",
                name: "Divider",
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_3warb732",
                type: "Text",
                path: "CocoTenDetailPage.body[0].children[3]",
                name: "Text",
                text: "住所",
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_v14g40k5",
                type: "Text",
                path: "CocoTenDetailPage.body[0].children[4]",
                name: "Text",
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_cmz4m4tx",
                type: "Text",
                path: "CocoTenDetailPage.body[0].children[5]",
                name: "Text",
                text: "メニュー",
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_r2soykvq",
                type: "Text",
                path: "CocoTenDetailPage.body[0].children[6]",
                name: "Text",
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_q4aux679",
                type: "Text",
                path: "CocoTenDetailPage.body[0].children[7]",
                name: "Text",
                text: "ゲスト特典",
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_a2e7z0ze",
                type: "Text",
                path: "CocoTenDetailPage.body[0].children[8]",
                name: "Text",
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_l4uhb287",
                type: "Button",
                path: "CocoTenDetailPage.body[0].children[9]",
                name: "InviteAtVenueButton",
                text: "このお店で待ち合わせるキャストを探す",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

