// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final cocotenManagementPageHandle = ffai.ProjectPageHandle<CocotenManagementPageParams, CocotenManagementPageState>(
  name: "CocotenManagementPage",
  key: "Scaffold_z35v7cvc",
  route: "admin-cocoten",
  params: const CocotenManagementPageParams(),
  state: const CocotenManagementPageState(),
  widgets: CocotenManagementPageWidgets.tree,
);

final class CocotenManagementPageParams {
  const CocotenManagementPageParams();
}

final class CocotenManagementPageState {
  const CocotenManagementPageState();
  ffai.ProjectStateFieldHandle get adminShopsList =>
      const ffai.ProjectStateFieldHandle(
        name: "adminShopsList",
        key: "a0xii3zo",
        typeName: "List<String>",
      );
  ffai.ProjectStateFieldHandle get cocotenGenresList =>
      const ffai.ProjectStateFieldHandle(
        name: "cocotenGenresList",
        key: "x6s1b1be",
        typeName: "List<String>",
      );
  ffai.ProjectStateFieldHandle get detailsGuestBenefits =>
      const ffai.ProjectStateFieldHandle(
        name: "detailsGuestBenefits",
        key: "mtou1yjw",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get detailsMenu =>
      const ffai.ProjectStateFieldHandle(
        name: "detailsMenu",
        key: "c21570b2",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get detailsPhotoUrl =>
      const ffai.ProjectStateFieldHandle(
        name: "detailsPhotoUrl",
        key: "suabmarb",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get detailsShopId =>
      const ffai.ProjectStateFieldHandle(
        name: "detailsShopId",
        key: "0expyakw",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get newShopBuilding =>
      const ffai.ProjectStateFieldHandle(
        name: "newShopBuilding",
        key: "cj0mkxic",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get newShopCity =>
      const ffai.ProjectStateFieldHandle(
        name: "newShopCity",
        key: "uc6p73la",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get newShopGenre =>
      const ffai.ProjectStateFieldHandle(
        name: "newShopGenre",
        key: "z6dxrur0",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get newShopName =>
      const ffai.ProjectStateFieldHandle(
        name: "newShopName",
        key: "mqko68eq",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get newShopPrefecture =>
      const ffai.ProjectStateFieldHandle(
        name: "newShopPrefecture",
        key: "wta8otdg",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get newShopTownBlock =>
      const ffai.ProjectStateFieldHandle(
        name: "newShopTownBlock",
        key: "xzelcyqy",
        typeName: "String",
      );
}

abstract final class CocotenManagementPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_z35v7cvc",
      type: "Scaffold",
      path: "CocotenManagementPage",
      name: "CocotenManagementPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_pm44kohy",
            type: "AppBar",
            path: "CocotenManagementPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_de9unj2u",
                  type: "Text",
                  path: "CocotenManagementPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "CocoTen店舗管理",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_a4j08hal",
            type: "Column",
            path: "CocotenManagementPage.body[0]",
            name: "CocotenManagementColumn",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_zpmabmpu",
                type: "Container",
                path: "CocotenManagementPage.body[0].children[0]",
                name: "CocotenManagementAccentBar",
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_lq31y084",
                type: "Container",
                path: "CocotenManagementPage.body[0].children[1]",
                name: "Container",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_ruu3u0o3",
                    type: "Row",
                    path: "CocotenManagementPage.body[0].children[1].children[0]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_v9iqlkje",
                        type: "Container",
                        path: "CocotenManagementPage.body[0].children[1].children[0].children[0]",
                        name: "Container",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_l7p1p9gb",
                        type: "Row",
                        path: "CocotenManagementPage.body[0].children[1].children[0].children[1]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_0eylvzgj",
                            type: "Icon",
                            path: "CocotenManagementPage.body[0].children[1].children[0].children[1].children[0]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_fr05g6fw",
                            type: "Text",
                            path: "CocotenManagementPage.body[0].children[1].children[0].children[1].children[1]",
                            name: "Text",
                            text: "新規店舗を追加",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Row_opryz7w1",
                type: "Row",
                path: "CocotenManagementPage.body[0].children[2]",
                name: "CocotenGenreMasterLinkRow",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_nzlmde02",
                    type: "Text",
                    path: "CocotenManagementPage.body[0].children[2].children[0]",
                    name: "Text",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_csnwbojn",
                    type: "Button",
                    path: "CocotenManagementPage.body[0].children[2].children[1]",
                    name: "AdminCocotenGenreMasterNavButton",
                    text: "ジャンルマスタ管理",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_r2bvds4p",
                type: "TextField",
                path: "CocotenManagementPage.body[0].children[3]",
                name: "NewShopNameField",
                text: "店舗名",
                triggers: const <String>[
                  "ON_TEXTFIELD_CHANGE",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_hn02yvyj",
                type: "TextField",
                path: "CocotenManagementPage.body[0].children[4]",
                name: "NewShopGenreField",
                text: "ジャンル（上記マスタのいずれかを入力）",
                triggers: const <String>[
                  "ON_TEXTFIELD_CHANGE",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_wc48nz72",
                type: "TextField",
                path: "CocotenManagementPage.body[0].children[5]",
                name: "NewShopPrefectureField",
                text: "都道府県",
                triggers: const <String>[
                  "ON_TEXTFIELD_CHANGE",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_vftr2qgc",
                type: "TextField",
                path: "CocotenManagementPage.body[0].children[6]",
                name: "NewShopCityField",
                text: "市区町村",
                triggers: const <String>[
                  "ON_TEXTFIELD_CHANGE",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_b8e9okes",
                type: "TextField",
                path: "CocotenManagementPage.body[0].children[7]",
                name: "NewShopTownBlockField",
                text: "町名番地",
                triggers: const <String>[
                  "ON_TEXTFIELD_CHANGE",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_9yw3bb6d",
                type: "TextField",
                path: "CocotenManagementPage.body[0].children[8]",
                name: "NewShopBuildingField",
                text: "建物名",
                triggers: const <String>[
                  "ON_TEXTFIELD_CHANGE",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_qraynmda",
                type: "Button",
                path: "CocotenManagementPage.body[0].children[9]",
                name: "AdminCreateShopButton",
                text: "店舗を追加",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Divider_fcjxpyxy",
                type: "Divider",
                path: "CocotenManagementPage.body[0].children[10]",
                name: "Divider",
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_9dzfu6m6",
                type: "Container",
                path: "CocotenManagementPage.body[0].children[11]",
                name: "Container",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_bc9ul4ds",
                    type: "Row",
                    path: "CocotenManagementPage.body[0].children[11].children[0]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_abyqczo0",
                        type: "Container",
                        path: "CocotenManagementPage.body[0].children[11].children[0].children[0]",
                        name: "Container",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_6elq6c5f",
                        type: "Row",
                        path: "CocotenManagementPage.body[0].children[11].children[0].children[1]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_v6zqkfvx",
                            type: "Icon",
                            path: "CocotenManagementPage.body[0].children[11].children[0].children[1].children[0]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_rb10deeb",
                            type: "Text",
                            path: "CocotenManagementPage.body[0].children[11].children[0].children[1].children[1]",
                            name: "Text",
                            text: "詳細編集（メニュー・特典・写真）",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_iqk9opwq",
                type: "Text",
                path: "CocotenManagementPage.body[0].children[12]",
                name: "Text",
                text: "下の一覧から店舗の「この店舗に反映」ボタンで、入力した内容をその店舗に反映します。",
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_1jc20wa7",
                type: "TextField",
                path: "CocotenManagementPage.body[0].children[13]",
                name: "DetailsMenuField",
                text: "メニュー情報",
                triggers: const <String>[
                  "ON_TEXTFIELD_CHANGE",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_lo86ea6s",
                type: "TextField",
                path: "CocotenManagementPage.body[0].children[14]",
                name: "DetailsGuestBenefitsField",
                text: "ゲスト用特典",
                triggers: const <String>[
                  "ON_TEXTFIELD_CHANGE",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_7fx8rxjw",
                type: "Button",
                path: "CocotenManagementPage.body[0].children[15]",
                name: "AdminUploadShopPhotoButton",
                text: "写真を選択してアップロード",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Image_nvo09099",
                type: "Image",
                path: "CocotenManagementPage.body[0].children[16]",
                name: "DetailsPhotoPreviewImage",
              ),
              ffai.ProjectWidgetHandle(
                key: "Divider_qvh6v5ug",
                type: "Divider",
                path: "CocotenManagementPage.body[0].children[17]",
                name: "Divider",
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_mdhrnhtu",
                type: "Container",
                path: "CocotenManagementPage.body[0].children[18]",
                name: "Container",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_or019ttw",
                    type: "Row",
                    path: "CocotenManagementPage.body[0].children[18].children[0]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_7ctt5vlh",
                        type: "Container",
                        path: "CocotenManagementPage.body[0].children[18].children[0].children[0]",
                        name: "Container",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_kubi4uu1",
                        type: "Row",
                        path: "CocotenManagementPage.body[0].children[18].children[0].children[1]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_66o7k737",
                            type: "Icon",
                            path: "CocotenManagementPage.body[0].children[18].children[0].children[1].children[0]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_i4yedk6m",
                            type: "Text",
                            path: "CocotenManagementPage.body[0].children[18].children[0].children[1].children[1]",
                            name: "Text",
                            text: "既存店舗",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_ptsz68p6",
                type: "ListView",
                path: "CocotenManagementPage.body[0].children[19]",
                name: "AdminShopsListView",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Card_0nz1g21k",
                    type: "Card",
                    path: "CocotenManagementPage.body[0].children[19].children[0]",
                    name: "Card",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_e3vnxjoh",
                        type: "Container",
                        path: "CocotenManagementPage.body[0].children[19].children[0].children[0]",
                        name: "Container",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_fj7mj1uv",
                            type: "Column",
                            path: "CocotenManagementPage.body[0].children[19].children[0].children[0].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_t9tttd4p",
                                type: "Row",
                                path: "CocotenManagementPage.body[0].children[19].children[0].children[0].children[0].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_uu0d5ukq",
                                    type: "Icon",
                                    path: "CocotenManagementPage.body[0].children[19].children[0].children[0].children[0].children[0].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_zzzlxuec",
                                    type: "Row",
                                    path: "CocotenManagementPage.body[0].children[19].children[0].children[0].children[0].children[0].children[1]",
                                    name: "Row",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_5dkye85z",
                                        type: "Container",
                                        path: "CocotenManagementPage.body[0].children[19].children[0].children[0].children[0].children[0].children[1].children[0]",
                                        name: "Container",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_yyw7clta",
                                            type: "Text",
                                            path: "CocotenManagementPage.body[0].children[19].children[0].children[0].children[0].children[0].children[1].children[0].children[0]",
                                            name: "Text",
                                            text: "公開中",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_xdw8tfgd",
                                        type: "Container",
                                        path: "CocotenManagementPage.body[0].children[19].children[0].children[0].children[0].children[0].children[1].children[1]",
                                        name: "Container",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_z5j7r4zo",
                                            type: "Text",
                                            path: "CocotenManagementPage.body[0].children[19].children[0].children[0].children[0].children[0].children[1].children[1].children[0]",
                                            name: "Text",
                                            text: "非公開",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_t5l4d0e8",
                                type: "Text",
                                path: "CocotenManagementPage.body[0].children[19].children[0].children[0].children[0].children[1]",
                                name: "Text",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_6u5pmwld",
                                type: "Row",
                                path: "CocotenManagementPage.body[0].children[19].children[0].children[0].children[0].children[2]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_zprim87p",
                                    type: "Button",
                                    path: "CocotenManagementPage.body[0].children[19].children[0].children[0].children[0].children[2].children[0]",
                                    name: "AdminToggleShopActiveButton",
                                    text: "公開/非公開切替",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_3bebfzi5",
                                    type: "Button",
                                    path: "CocotenManagementPage.body[0].children[19].children[0].children[0].children[0].children[2].children[1]",
                                    name: "AdminRemoveShopButton",
                                    text: "削除",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Button_p88cfv8q",
                                type: "Button",
                                path: "CocotenManagementPage.body[0].children[19].children[0].children[0].children[0].children[3]",
                                name: "AdminApplyShopDetailsButton",
                                text: "この店舗に反映（メニュー・特典・写真）",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

