// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final kycHandle = ffai.ProjectPageHandle<KycParams, KycState>(
  name: "Kyc",
  key: "Scaffold_tf05hd4t",
  route: "",
  params: const KycParams(),
  state: const KycState(),
  widgets: KycWidgets.tree,
);

final class KycParams {
  const KycParams();
}

final class KycState {
  const KycState();
  ffai.ProjectStateFieldHandle get kycDocUrl =>
      const ffai.ProjectStateFieldHandle(
        name: "kycDocUrl",
        key: "8ah31fza",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get kycSelfieUrl =>
      const ffai.ProjectStateFieldHandle(
        name: "kycSelfieUrl",
        key: "okiziqhh",
        typeName: "String",
      );
}

abstract final class KycWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_tf05hd4t",
      type: "Scaffold",
      path: "Kyc",
      name: "Kyc",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_vgd4qzop",
            type: "AppBar",
            path: "Kyc.appBar[0]",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Stack_43otmfh2",
                  type: "Stack",
                  path: "Kyc.appBar[0].title[0]",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Row_p68vl0vw",
                      type: "Row",
                      path: "Kyc.appBar[0].title[0].children[0]",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Icon_7f5t6rr5",
                          type: "Icon",
                          path: "Kyc.appBar[0].title[0].children[0].children[0]",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Image_gnbe0x7a",
                          type: "Image",
                          path: "Kyc.appBar[0].title[0].children[0].children[1]",
                          triggers: const <String>[
                            "ON_TAP",
                          ],
                        ),
                      ],
                    ),
                    ffai.ProjectWidgetHandle(
                      key: "Text_yjdokd8r",
                      type: "Text",
                      path: "Kyc.appBar[0].title[0].children[1]",
                      text: "本人確認書類の提出",
                    ),
                  ],
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_tpp6mp73",
            type: "Container",
            path: "Kyc.body[0]",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_kxfln3uo",
                type: "Column",
                path: "Kyc.body[0].children[0]",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_0zeharc6",
                    type: "Text",
                    path: "Kyc.body[0].children[0].children[0]",
                    text: "本人確認書類をアップロードしてください",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Card_zea5062c",
                    type: "Card",
                    path: "Kyc.body[0].children[0].children[1]",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_a6ao8mvb",
                        type: "Container",
                        path: "Kyc.body[0].children[0].children[1].children[0]",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_px782c2u",
                            type: "Column",
                            path: "Kyc.body[0].children[0].children[1].children[0].children[0]",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_i4667ata",
                                type: "Container",
                                path: "Kyc.body[0].children[0].children[1].children[0].children[0].children[0]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Image_caclcv9m",
                                    type: "Image",
                                    path: "Kyc.body[0].children[0].children[1].children[0].children[0].children[0].children[0]",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_g7rmhcmm",
                                type: "Text",
                                path: "Kyc.body[0].children[0].children[1].children[0].children[0].children[1]",
                                text: "運転免許証・パスポート・マイナンバーカード・小型船舶操縦士免許証等",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_44dsdfuo",
                                type: "Text",
                                path: "Kyc.body[0].children[0].children[1].children[0].children[0].children[2]",
                                name: "KycDocUploadStatus",
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Card_mrn1fobu",
                    type: "Card",
                    path: "Kyc.body[0].children[0].children[2]",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_zjx8ggz4",
                        type: "Container",
                        path: "Kyc.body[0].children[0].children[2].children[0]",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_ddvgm2q7",
                            type: "Column",
                            path: "Kyc.body[0].children[0].children[2].children[0].children[0]",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_h95e441s",
                                type: "Container",
                                path: "Kyc.body[0].children[0].children[2].children[0].children[0].children[0]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Image_8r83ksqp",
                                    type: "Image",
                                    path: "Kyc.body[0].children[0].children[2].children[0].children[0].children[0].children[0]",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_9ul8sx8w",
                                type: "Text",
                                path: "Kyc.body[0].children[0].children[2].children[0].children[0].children[1]",
                                text: "顔がはっきり写った写真をご用意ください",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_v496fngr",
                                type: "Text",
                                path: "Kyc.body[0].children[0].children[2].children[0].children[0].children[2]",
                                name: "KycSelfieUploadStatus",
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Row_osotf640",
                    type: "Row",
                    path: "Kyc.body[0].children[0].children[3]",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Icon_99m1cz4k",
                        type: "Icon",
                        path: "Kyc.body[0].children[0].children[3].children[0]",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_qd9o2ymr",
                        type: "Text",
                        path: "Kyc.body[0].children[0].children[3].children[1]",
                        text: "アップロード時の注意事項",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_7uzxgwtq",
                    type: "Text",
                    path: "Kyc.body[0].children[0].children[4]",
                    text: "・画像は鮮明で文字が読めるものをご使用ください",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_9cblwxid",
                    type: "Text",
                    path: "Kyc.body[0].children[0].children[5]",
                    text: "・ファイル形式：JPG / PNG（最大10MB）",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_myxgy3mt",
                    type: "Text",
                    path: "Kyc.body[0].children[0].children[6]",
                    text: "・審査には1〜3営業日かかる場合があります",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Divider_r0a3brb1",
                    type: "Divider",
                    path: "Kyc.body[0].children[0].children[7]",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_zarp9j5y",
                    type: "Button",
                    path: "Kyc.body[0].children[0].children[8]",
                    name: "KycSubmitButton",
                    text: "提出する",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

