// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final kycReviewPageHandle = ffai.ProjectPageHandle<KycReviewPageParams, KycReviewPageState>(
  name: "KycReviewPage",
  key: "Scaffold_x33leoaa",
  route: "kyc-review",
  params: const KycReviewPageParams(),
  state: const KycReviewPageState(),
  widgets: KycReviewPageWidgets.tree,
);

final class KycReviewPageParams {
  const KycReviewPageParams();
}

final class KycReviewPageState {
  const KycReviewPageState();
  ffai.ProjectStateFieldHandle get isAdminUser =>
      const ffai.ProjectStateFieldHandle(
        name: "isAdminUser",
        key: "zxrcghki",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get pendingKycList =>
      const ffai.ProjectStateFieldHandle(
        name: "pendingKycList",
        key: "z3a1xedh",
        typeName: "List<String>",
      );
}

abstract final class KycReviewPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_x33leoaa",
      type: "Scaffold",
      path: "KycReviewPage",
      name: "KycReviewPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_wv146igl",
            type: "AppBar",
            path: "KycReviewPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_woknwgt6",
                  type: "Text",
                  path: "KycReviewPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "KYC審査",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_wfyfe069",
            type: "Column",
            path: "KycReviewPage.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Text_sqkl0kj7",
                type: "Text",
                path: "KycReviewPage.body[0].children[0]",
                name: "Text",
                text: "管理者権限がありません。",
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_ohcx81fg",
                type: "ListView",
                path: "KycReviewPage.body[0].children[1]",
                name: "ListView",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Card_njfbsv61",
                    type: "Card",
                    path: "KycReviewPage.body[0].children[1].children[0]",
                    name: "KycReviewItemCard",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_pvc7hgn3",
                        type: "Container",
                        path: "KycReviewPage.body[0].children[1].children[0].children[0]",
                        name: "Container",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_mlfa819k",
                            type: "Column",
                            path: "KycReviewPage.body[0].children[1].children[0].children[0].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_vkn5jdjo",
                                type: "Text",
                                path: "KycReviewPage.body[0].children[1].children[0].children[0].children[0].children[0]",
                                name: "Text",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_z5mcruq0",
                                type: "Text",
                                path: "KycReviewPage.body[0].children[1].children[0].children[0].children[0].children[1]",
                                name: "Text",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_05fsaq0l",
                                type: "Row",
                                path: "KycReviewPage.body[0].children[1].children[0].children[0].children[0].children[2]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Image_dd4nmc9v",
                                    type: "Image",
                                    path: "KycReviewPage.body[0].children[1].children[0].children[0].children[0].children[2].children[0]",
                                    name: "KycReviewDocImage",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Image_t5x0rbso",
                                    type: "Image",
                                    path: "KycReviewPage.body[0].children[1].children[0].children[0].children[0].children[2].children[1]",
                                    name: "KycReviewSelfieImage",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_699yb1fs",
                                type: "Row",
                                path: "KycReviewPage.body[0].children[1].children[0].children[0].children[0].children[3]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_xxyotqbe",
                                    type: "Button",
                                    path: "KycReviewPage.body[0].children[1].children[0].children[0].children[0].children[3].children[0]",
                                    name: "KycApproveButton",
                                    text: "承認する",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_qjwr7knr",
                                    type: "Button",
                                    path: "KycReviewPage.body[0].children[1].children[0].children[0].children[0].children[3].children[1]",
                                    name: "KycRejectButton",
                                    text: "却下する",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

