// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final macchaChatsHandle = ffai.ProjectPageHandle<MacchaChatsParams, MacchaChatsState>(
  name: "MacchaChats",
  key: "Scaffold_x6lf2wag",
  route: "",
  params: const MacchaChatsParams(),
  state: const MacchaChatsState(),
  widgets: MacchaChatsWidgets.tree,
);

final class MacchaChatsParams {
  const MacchaChatsParams();
}

final class MacchaChatsState {
  const MacchaChatsState();
}

abstract final class MacchaChatsWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_x6lf2wag",
      type: "Scaffold",
      path: "MacchaChats",
      name: "MacchaChats",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_gvr6e51y",
            type: "AppBar",
            path: "MacchaChats.appBar[0]",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Row_onaf3cfz",
                  type: "Row",
                  path: "MacchaChats.appBar[0].title[0]",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Row_51wuhi3n",
                      type: "Row",
                      path: "MacchaChats.appBar[0].title[0].children[0]",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Icon_rtfa55ss",
                          type: "Icon",
                          path: "MacchaChats.appBar[0].title[0].children[0].children[0]",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Image_wwzammb9",
                          type: "Image",
                          path: "MacchaChats.appBar[0].title[0].children[0].children[1]",
                          triggers: const <String>[
                            "ON_TAP",
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_un0xb067",
            type: "Container",
            path: "MacchaChats.body[0]",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_e9kwqcdq",
                type: "Column",
                path: "MacchaChats.body[0].children[0]",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Card_klhzk0l1",
                    type: "Card",
                    path: "MacchaChats.body[0].children[0].children[0]",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_csa6zz07",
                        type: "Container",
                        path: "MacchaChats.body[0].children[0].children[0].children[0]",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_xuyify4c",
                            type: "Row",
                            path: "MacchaChats.body[0].children[0].children[0].children[0].children[0]",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_tgliisbh",
                                type: "Container",
                                path: "MacchaChats.body[0].children[0].children[0].children[0].children[0].children[0]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "CircleImage_icxkap1q",
                                    type: "CircleImage",
                                    path: "MacchaChats.body[0].children[0].children[0].children[0].children[0].children[0].children[0]",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_xy2lnok8",
                                type: "Text",
                                path: "MacchaChats.body[0].children[0].children[0].children[0].children[0].children[1]",
                                text: "ゲスト",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Icon_leq2e03r",
                                type: "Icon",
                                path: "MacchaChats.body[0].children[0].children[0].children[0].children[0].children[2]",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_ric3y3ea",
                                type: "Container",
                                path: "MacchaChats.body[0].children[0].children[0].children[0].children[0].children[3]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "CircleImage_i92wz4ne",
                                    type: "CircleImage",
                                    path: "MacchaChats.body[0].children[0].children[0].children[0].children[0].children[3].children[0]",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_xyrrvoiq",
                                type: "Text",
                                path: "MacchaChats.body[0].children[0].children[0].children[0].children[0].children[4]",
                                text: "キャスト",
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_ecoxe99x",
                    type: "Container",
                    path: "MacchaChats.body[0].children[0].children[1]",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_qm034hl4",
                        type: "Text",
                        path: "MacchaChats.body[0].children[0].children[1].children[0]",
                        text: "マッチャ",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListView_84hpa09g",
                    type: "ListView",
                    path: "MacchaChats.body[0].children[0].children[2]",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_mf90dt7n",
                        type: "Column",
                        path: "MacchaChats.body[0].children[0].children[2].children[0]",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_qhpxatt1",
                            type: "Row",
                            path: "MacchaChats.body[0].children[0].children[2].children[0].children[0]",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_dcbliqhn",
                                type: "Column",
                                path: "MacchaChats.body[0].children[0].children[2].children[0].children[0].children[0]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_l654ka8s",
                                    type: "Container",
                                    path: "MacchaChats.body[0].children[0].children[2].children[0].children[0].children[0].children[0]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "CircleImage_zt7h2h5n",
                                        type: "CircleImage",
                                        path: "MacchaChats.body[0].children[0].children[2].children[0].children[0].children[0].children[0].children[0]",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_jyegkeb8",
                                    type: "Text",
                                    path: "MacchaChats.body[0].children[0].children[2].children[0].children[0].children[0].children[1]",
                                    text: "ゲスト",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_43gevpej",
                                type: "Container",
                                path: "MacchaChats.body[0].children[0].children[2].children[0].children[0].children[1]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_lkqi59zj",
                                    type: "Column",
                                    path: "MacchaChats.body[0].children[0].children[2].children[0].children[0].children[1].children[0]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_oq28b6hy",
                                        type: "Text",
                                        path: "MacchaChats.body[0].children[0].children[2].children[0].children[0].children[1].children[0].children[0]",
                                        text: "Hello World",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_ln1remzz",
                                        type: "Text",
                                        path: "MacchaChats.body[0].children[0].children[2].children[0].children[0].children[1].children[0].children[1]",
                                        text: "Hello World",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Row_7r4o0zry",
                            type: "Row",
                            path: "MacchaChats.body[0].children[0].children[2].children[0].children[1]",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_v5xfuwvv",
                                type: "Container",
                                path: "MacchaChats.body[0].children[0].children[2].children[0].children[1].children[0]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_mvz7tmij",
                                    type: "Column",
                                    path: "MacchaChats.body[0].children[0].children[2].children[0].children[1].children[0].children[0]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_dsbaa14k",
                                        type: "Text",
                                        path: "MacchaChats.body[0].children[0].children[2].children[0].children[1].children[0].children[0].children[0]",
                                        text: "Hello World",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_w6tp73fn",
                                        type: "Text",
                                        path: "MacchaChats.body[0].children[0].children[2].children[0].children[1].children[0].children[0].children[1]",
                                        text: "Hello World",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Column_3ab8g4k0",
                                type: "Column",
                                path: "MacchaChats.body[0].children[0].children[2].children[0].children[1].children[1]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_ba8dxipd",
                                    type: "Container",
                                    path: "MacchaChats.body[0].children[0].children[2].children[0].children[1].children[1].children[0]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "CircleImage_qiato23e",
                                        type: "CircleImage",
                                        path: "MacchaChats.body[0].children[0].children[2].children[0].children[1].children[1].children[0].children[0]",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_61t18uup",
                                    type: "Text",
                                    path: "MacchaChats.body[0].children[0].children[2].children[0].children[1].children[1].children[1]",
                                    text: "キャスト",
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_wdppvjci",
                    type: "Container",
                    path: "MacchaChats.body[0].children[0].children[3]",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_et75ls2c",
                        type: "Row",
                        path: "MacchaChats.body[0].children[0].children[3].children[0]",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_8bfac8qn",
                            type: "Icon",
                            path: "MacchaChats.body[0].children[0].children[3].children[0].children[0]",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "TextField_iucuj771",
                            type: "TextField",
                            path: "MacchaChats.body[0].children[0].children[3].children[0].children[1]",
                            text: "メッセージ",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_yc7c5u08",
                            type: "Container",
                            path: "MacchaChats.body[0].children[0].children[3].children[0].children[2]",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_jm5abnro",
                                type: "Icon",
                                path: "MacchaChats.body[0].children[0].children[3].children[0].children[2].children[0]",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

