// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final macchaPageHandle = ffai.ProjectPageHandle<MacchaPageParams, MacchaPageState>(
  name: "MacchaPage",
  key: "Scaffold_hx45w9vd",
  route: "",
  params: const MacchaPageParams(),
  state: const MacchaPageState(),
  widgets: MacchaPageWidgets.tree,
);

final class MacchaPageParams {
  const MacchaPageParams();
}

final class MacchaPageState {
  const MacchaPageState();
  ffai.ProjectStateFieldHandle get matchaFilter =>
      const ffai.ProjectStateFieldHandle(
        name: "matchaFilter",
        key: "yphl9c2g",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get myChatRoomsList =>
      const ffai.ProjectStateFieldHandle(
        name: "myChatRoomsList",
        key: "3eawfpq1",
        typeName: "List<String>",
      );
  ffai.ProjectStateFieldHandle get visibleMatchaList =>
      const ffai.ProjectStateFieldHandle(
        name: "visibleMatchaList",
        key: "33uot43y",
        typeName: "List<String>",
      );
}

abstract final class MacchaPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_hx45w9vd",
      type: "Scaffold",
      path: "MacchaPage",
      name: "MacchaPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_rd41pl12",
            type: "AppBar",
            path: "MacchaPage.appBar[0]",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Row_xpju64y6",
                  type: "Row",
                  path: "MacchaPage.appBar[0].title[0]",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Image_a01mlb9d",
                      type: "Image",
                      path: "MacchaPage.appBar[0].title[0].children[0]",
                      triggers: const <String>[
                        "ON_TAP",
                      ],
                    ),
                    ffai.ProjectWidgetHandle(
                      key: "Row_6k761ev3",
                      type: "Row",
                      path: "MacchaPage.appBar[0].title[0].children[1]",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Column_m22bph3p",
                          type: "Column",
                          path: "MacchaPage.appBar[0].title[0].children[1].children[0]",
                          triggers: const <String>[
                            "ON_TAP",
                          ],
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Icon_fy95oz32",
                              type: "Icon",
                              path: "MacchaPage.appBar[0].title[0].children[1].children[0].children[0]",
                            ),
                            ffai.ProjectWidgetHandle(
                              key: "Text_rur5ympv",
                              type: "Text",
                              path: "MacchaPage.appBar[0].title[0].children[1].children[0].children[1]",
                              text: "検 索",
                            ),
                          ],
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Column_0mgdi479",
                          type: "Column",
                          path: "MacchaPage.appBar[0].title[0].children[1].children[1]",
                          triggers: const <String>[
                            "ON_TAP",
                          ],
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Icon_0vz8dbs7",
                              type: "Icon",
                              path: "MacchaPage.appBar[0].title[0].children[1].children[1].children[0]",
                            ),
                            ffai.ProjectWidgetHandle(
                              key: "Text_rzf7t3wv",
                              type: "Text",
                              path: "MacchaPage.appBar[0].title[0].children[1].children[1].children[1]",
                              text: "お知らせ",
                            ),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Stack_tgw6w5tj",
            type: "Stack",
            path: "MacchaPage.body[0]",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_mdkn7ng8",
                type: "Container",
                path: "MacchaPage.body[0].children[0]",
                componentName: "ButtomNaviComp",
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_n8pyumdf",
                type: "Container",
                path: "MacchaPage.body[0].children[1]",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "ListView_w1igv74t",
                    type: "ListView",
                    path: "MacchaPage.body[0].children[1].children[0]",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_8g095usw",
                        type: "Column",
                        path: "MacchaPage.body[0].children[1].children[0].children[0]",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_cbpo2m1t",
                            type: "Row",
                            path: "MacchaPage.body[0].children[1].children[0].children[0].children[0]",
                            name: "MatchaFilterTabs",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_tdhlzt7u",
                                type: "Container",
                                path: "MacchaPage.body[0].children[1].children[0].children[0].children[0].children[0]",
                                name: "MatchaTab_all",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_dr8nsm24",
                                    type: "Text",
                                    path: "MacchaPage.body[0].children[1].children[0].children[0].children[0].children[0].children[0]",
                                    name: "Text",
                                    text: "すべて",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_yr8n2xi3",
                                type: "Container",
                                path: "MacchaPage.body[0].children[1].children[0].children[0].children[0].children[1]",
                                name: "MatchaTab_new",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_qrmx21ek",
                                    type: "Text",
                                    path: "MacchaPage.body[0].children[1].children[0].children[0].children[0].children[1].children[0]",
                                    name: "Text",
                                    text: "新しい",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_lkdo6ezo",
                                type: "Container",
                                path: "MacchaPage.body[0].children[1].children[0].children[0].children[0].children[2]",
                                name: "MatchaTab_not_interacted",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_o5lhhukd",
                                    type: "Text",
                                    path: "MacchaPage.body[0].children[1].children[0].children[0].children[0].children[2].children[0]",
                                    name: "Text",
                                    text: "未交流",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_tbvm3xzf",
                                type: "Container",
                                path: "MacchaPage.body[0].children[1].children[0].children[0].children[0].children[3]",
                                name: "MatchaTab_interacted",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_0sb0de6e",
                                    type: "Text",
                                    path: "MacchaPage.body[0].children[1].children[0].children[0].children[0].children[3].children[0]",
                                    name: "Text",
                                    text: "交流済み",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_lh11kn9b",
                                type: "Container",
                                path: "MacchaPage.body[0].children[1].children[0].children[0].children[0].children[4]",
                                name: "MatchaTab_declined",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_8el30apl",
                                    type: "Text",
                                    path: "MacchaPage.body[0].children[1].children[0].children[0].children[0].children[4].children[0]",
                                    name: "Text",
                                    text: "断られた",
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Divider_jwtm0qhw",
                            type: "Divider",
                            path: "MacchaPage.body[0].children[1].children[0].children[0].children[1]",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_vghagqde",
                            type: "Container",
                            path: "MacchaPage.body[0].children[1].children[0].children[0].children[2]",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "ListView_moyozme3",
                                type: "ListView",
                                path: "MacchaPage.body[0].children[1].children[0].children[0].children[2].children[0]",
                                name: "MatchaItemsListView",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Card_gjfssn7g",
                                    type: "Card",
                                    path: "MacchaPage.body[0].children[1].children[0].children[0].children[2].children[0].children[0]",
                                    name: "MatchaItemCard",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_48tv58y1",
                                        type: "Container",
                                        path: "MacchaPage.body[0].children[1].children[0].children[0].children[2].children[0].children[0].children[0]",
                                        name: "Container",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Row_oc7rkzuk",
                                            type: "Row",
                                            path: "MacchaPage.body[0].children[1].children[0].children[0].children[2].children[0].children[0].children[0].children[0]",
                                            name: "Row",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "CircleImage_t8x5yfi6",
                                                type: "CircleImage",
                                                path: "MacchaPage.body[0].children[1].children[0].children[0].children[2].children[0].children[0].children[0].children[0].children[0]",
                                                name: "Avatar",
                                              ),
                                              ffai.ProjectWidgetHandle(
                                                key: "Column_t58kd8ts",
                                                type: "Column",
                                                path: "MacchaPage.body[0].children[1].children[0].children[0].children[2].children[0].children[0].children[0].children[0].children[1]",
                                                name: "Column",
                                                children: <ffai.ProjectWidgetHandle>[
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Text_dorgfld0",
                                                    type: "Text",
                                                    path: "MacchaPage.body[0].children[1].children[0].children[0].children[2].children[0].children[0].children[0].children[0].children[1].children[0]",
                                                    name: "Text",
                                                  ),
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Text_t43tal25",
                                                    type: "Text",
                                                    path: "MacchaPage.body[0].children[1].children[0].children[0].children[2].children[0].children[0].children[0].children[0].children[1].children[1]",
                                                    name: "Text",
                                                  ),
                                                ],
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

