// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final macchaChatsHandle = ffai.ProjectPageHandle<MacchaChatsParams, MacchaChatsState>(
  name: "MacchaChats",
  key: "Scaffold_x6lf2wag",
  route: "",
  params: const MacchaChatsParams(),
  state: const MacchaChatsState(),
  widgets: MacchaChatsWidgets.tree,
);

final class MacchaChatsParams {
  const MacchaChatsParams();
  ffai.ProjectParamHandle get resId =>
      const ffai.ProjectParamHandle(
        name: "resId",
        key: "tsz8161u",
        typeName: "String",
      );
}

final class MacchaChatsState {
  const MacchaChatsState();
  ffai.ProjectStateFieldHandle get chatMessagesList =>
      const ffai.ProjectStateFieldHandle(
        name: "chatMessagesList",
        key: "q9m5wehb",
        typeName: "List<String>",
      );
  ffai.ProjectStateFieldHandle get counterpartNickname =>
      const ffai.ProjectStateFieldHandle(
        name: "counterpartNickname",
        key: "bd4jjq8q",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get counterpartPhoto =>
      const ffai.ProjectStateFieldHandle(
        name: "counterpartPhoto",
        key: "hafcq0um",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get newMessageText =>
      const ffai.ProjectStateFieldHandle(
        name: "newMessageText",
        key: "kip5oawk",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get roomActive =>
      const ffai.ProjectStateFieldHandle(
        name: "roomActive",
        key: "jxh13mb6",
        typeName: "Boolean",
      );
}

abstract final class MacchaChatsWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_x6lf2wag",
      type: "Scaffold",
      path: "MacchaChats",
      name: "MacchaChats",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_gvr6e51y",
            type: "AppBar",
            path: "MacchaChats.appBar[0]",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Row_onaf3cfz",
                  type: "Row",
                  path: "MacchaChats.appBar[0].title[0]",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Row_51wuhi3n",
                      type: "Row",
                      path: "MacchaChats.appBar[0].title[0].children[0]",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Icon_rtfa55ss",
                          type: "Icon",
                          path: "MacchaChats.appBar[0].title[0].children[0].children[0]",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Image_wwzammb9",
                          type: "Image",
                          path: "MacchaChats.appBar[0].title[0].children[0].children[1]",
                          triggers: const <String>[
                            "ON_TAP",
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_un0xb067",
            type: "Container",
            path: "MacchaChats.body[0]",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_e9kwqcdq",
                type: "Column",
                path: "MacchaChats.body[0].children[0]",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Card_klhzk0l1",
                    type: "Card",
                    path: "MacchaChats.body[0].children[0].children[0]",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_csa6zz07",
                        type: "Container",
                        path: "MacchaChats.body[0].children[0].children[0].children[0]",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_7l6ksffh",
                            type: "Row",
                            path: "MacchaChats.body[0].children[0].children[0].children[0].children[0]",
                            name: "ChatHeaderRow",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Stack_z6woy5q0",
                                type: "Stack",
                                path: "MacchaChats.body[0].children[0].children[0].children[0].children[0].children[0]",
                                name: "ChatCounterpartAvatar",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "CircleImage_62fiub4t",
                                    type: "CircleImage",
                                    path: "MacchaChats.body[0].children[0].children[0].children[0].children[0].children[0].children[0]",
                                    name: "ChatCounterpartAvatarReal",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Image_6nj1sx6g",
                                    type: "Image",
                                    path: "MacchaChats.body[0].children[0].children[0].children[0].children[0].children[0].children[1]",
                                    name: "ChatCounterpartAvatarFallback",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_5y0dzqpf",
                                type: "Text",
                                path: "MacchaChats.body[0].children[0].children[0].children[0].children[0].children[1]",
                                name: "Text",
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_ecoxe99x",
                    type: "Container",
                    path: "MacchaChats.body[0].children[0].children[1]",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_qm034hl4",
                        type: "Text",
                        path: "MacchaChats.body[0].children[0].children[1].children[0]",
                        text: "マッチャ",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListView_2xvonypa",
                    type: "ListView",
                    path: "MacchaChats.body[0].children[0].children[2]",
                    name: "ChatMessagesListView",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_6jfjda54",
                        type: "Container",
                        path: "MacchaChats.body[0].children[0].children[2].children[0]",
                        name: "Container",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_paup90w6",
                            type: "Row",
                            path: "MacchaChats.body[0].children[0].children[2].children[0].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_qpvks4nz",
                                type: "Text",
                                path: "MacchaChats.body[0].children[0].children[2].children[0].children[0].children[0]",
                                name: "Text",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_ybuilwyx",
                                type: "Text",
                                path: "MacchaChats.body[0].children[0].children[2].children[0].children[0].children[1]",
                                name: "Text",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_ssjmkhon",
                                type: "Text",
                                path: "MacchaChats.body[0].children[0].children[2].children[0].children[0].children[2]",
                                name: "Text",
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_wdppvjci",
                    type: "Container",
                    path: "MacchaChats.body[0].children[0].children[3]",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_et75ls2c",
                        type: "Row",
                        path: "MacchaChats.body[0].children[0].children[3].children[0]",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_8bfac8qn",
                            type: "Icon",
                            path: "MacchaChats.body[0].children[0].children[3].children[0].children[0]",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "TextField_82xeqnv5",
                            type: "TextField",
                            path: "MacchaChats.body[0].children[0].children[3].children[0].children[1]",
                            name: "ChatMessageInput",
                            text: "メッセージ",
                            triggers: const <String>[
                              "ON_TEXTFIELD_CHANGE",
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_yc7c5u08",
                            type: "Container",
                            path: "MacchaChats.body[0].children[0].children[3].children[0].children[2]",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_jm5abnro",
                                type: "Icon",
                                path: "MacchaChats.body[0].children[0].children[3].children[0].children[2].children[0]",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

