// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final processedEventsPageHandle = ffai.ProjectPageHandle<ProcessedEventsPageParams, ProcessedEventsPageState>(
  name: "ProcessedEventsPage",
  key: "Scaffold_8fswb8sn",
  route: "admin-processed-events",
  params: const ProcessedEventsPageParams(),
  state: const ProcessedEventsPageState(),
  widgets: ProcessedEventsPageWidgets.tree,
);

final class ProcessedEventsPageParams {
  const ProcessedEventsPageParams();
}

final class ProcessedEventsPageState {
  const ProcessedEventsPageState();
  ffai.ProjectStateFieldHandle get processedEventsList =>
      const ffai.ProjectStateFieldHandle(
        name: "processedEventsList",
        key: "y2a5ai1b",
        typeName: "List<String>",
      );
}

abstract final class ProcessedEventsPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_8fswb8sn",
      type: "Scaffold",
      path: "ProcessedEventsPage",
      name: "ProcessedEventsPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_41d7nrsi",
            type: "AppBar",
            path: "ProcessedEventsPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_deouahvt",
                  type: "Text",
                  path: "ProcessedEventsPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "ProcessedEvents",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_5kft3gii",
            type: "Column",
            path: "ProcessedEventsPage.body[0]",
            name: "ProcessedEventsWithExportColumn",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Button_ad1x2ovi",
                type: "Button",
                path: "ProcessedEventsPage.body[0].children[0]",
                name: "AdminExportProcessedEventsCsvButton",
                text: "CSVをコピー（読み込み済みの行のみ）",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Divider_yninxc7p",
                type: "Divider",
                path: "ProcessedEventsPage.body[0].children[1]",
                name: "Divider",
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_2tcy6y9j",
                type: "ListView",
                path: "ProcessedEventsPage.body[0].children[2]",
                name: "ProcessedEventsListView",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Card_pp9k4h1p",
                    type: "Card",
                    path: "ProcessedEventsPage.body[0].children[2].children[0]",
                    name: "Card",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_djhsd60v",
                        type: "Container",
                        path: "ProcessedEventsPage.body[0].children[2].children[0].children[0]",
                        name: "Container",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_aotd3m0u",
                            type: "Text",
                            path: "ProcessedEventsPage.body[0].children[2].children[0].children[0].children[0]",
                            name: "Text",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

