// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final reservationFormHandle = ffai.ProjectPageHandle<ReservationFormParams, ReservationFormState>(
  name: "ReservationForm",
  key: "Scaffold_zxpwg49d",
  route: "",
  params: const ReservationFormParams(),
  state: const ReservationFormState(),
  widgets: ReservationFormWidgets.tree,
);

final class ReservationFormParams {
  const ReservationFormParams();
}

final class ReservationFormState {
  const ReservationFormState();
}

abstract final class ReservationFormWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_zxpwg49d",
      type: "Scaffold",
      path: "ReservationForm",
      name: "ReservationForm",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_6tef4hkp",
            type: "AppBar",
            path: "ReservationForm.appBar[0]",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Stack_jwo4jir1",
                  type: "Stack",
                  path: "ReservationForm.appBar[0].title[0]",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Row_8mfvbxip",
                      type: "Row",
                      path: "ReservationForm.appBar[0].title[0].children[0]",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Icon_1ll7h40h",
                          type: "Icon",
                          path: "ReservationForm.appBar[0].title[0].children[0].children[0]",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Image_1iaa6oop",
                          type: "Image",
                          path: "ReservationForm.appBar[0].title[0].children[0].children[1]",
                          triggers: const <String>[
                            "ON_TAP",
                          ],
                        ),
                      ],
                    ),
                    ffai.ProjectWidgetHandle(
                      key: "Text_thjuaz0l",
                      type: "Text",
                      path: "ReservationForm.appBar[0].title[0].children[1]",
                      text: "お誘いフォーム",
                    ),
                  ],
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_53fh3rdg",
            type: "Container",
            path: "ReservationForm.body[0]",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_3ju8og9s",
                type: "Column",
                path: "ReservationForm.body[0].children[0]",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_bo2cnntv",
                    type: "Text",
                    path: "ReservationForm.body[0].children[0].children[0]",
                    text: "お誘いフォーム",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_ydwemjny",
                    type: "Text",
                    path: "ReservationForm.body[0].children[0].children[1]",
                    text: "お誘い内容をご記入ください",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Card_szt8ltpx",
                    type: "Card",
                    path: "ReservationForm.body[0].children[0].children[2]",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_z3xp97hr",
                        type: "Container",
                        path: "ReservationForm.body[0].children[0].children[2].children[0]",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_k5uw75hg",
                            type: "Column",
                            path: "ReservationForm.body[0].children[0].children[2].children[0].children[0]",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_gmohflkk",
                                type: "Row",
                                path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[0]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_6m9zr1du",
                                    type: "Icon",
                                    path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[0].children[0]",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_o7f4nlh4",
                                    type: "Text",
                                    path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[0].children[1]",
                                    text: "お誘い内容",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Divider_8qaffiu4",
                                type: "Divider",
                                path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[1]",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_df1xwgy2",
                                type: "Row",
                                path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[2]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_axfpteou",
                                    type: "Column",
                                    path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[2].children[0]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_gwd1epw8",
                                        type: "Text",
                                        path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[2].children[0].children[0]",
                                        text: "日　付",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_8is5q6ti",
                                        type: "Container",
                                        path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[2].children[0].children[1]",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_60ilqvjv",
                                            type: "Icon",
                                            path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[2].children[0].children[1].children[0]",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_d0j6d4ks",
                                type: "Row",
                                path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[3]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_uam212vu",
                                    type: "Column",
                                    path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[3].children[0]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_pwdethom",
                                        type: "Text",
                                        path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[3].children[0].children[0]",
                                        text: "時間帯",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "DropDown_zufoed9k",
                                        type: "DropDown",
                                        path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[3].children[0].children[1]",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_wmcxj81f",
                                type: "Row",
                                path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[4]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_s2v69vqe",
                                    type: "Column",
                                    path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[4].children[0]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_6v83iznl",
                                        type: "Text",
                                        path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[4].children[0].children[0]",
                                        text: "交流時間",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "DropDown_hqnthj6t",
                                        type: "DropDown",
                                        path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[4].children[0].children[1]",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_dvhp0o5z",
                                type: "Row",
                                path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[5]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_7xfv4nie",
                                    type: "Column",
                                    path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[5].children[0]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_fn1jy56x",
                                        type: "Text",
                                        path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[5].children[0].children[0]",
                                        text: "交流開始時間",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "DropDown_lf1zrpbg",
                                        type: "DropDown",
                                        path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[5].children[0].children[1]",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_5tjppo0n",
                                type: "Row",
                                path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[6]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_xeu8ro29",
                                    type: "Column",
                                    path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[6].children[0]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_qnqfrvrg",
                                        type: "Text",
                                        path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[6].children[0].children[0]",
                                        text: "延長予定の有無",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "DropDown_ne646169",
                                        type: "DropDown",
                                        path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[6].children[0].children[1]",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_kwchb0yn",
                                type: "Row",
                                path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[7]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_heihxo2z",
                                    type: "Column",
                                    path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[7].children[0]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_wemiln4i",
                                        type: "Text",
                                        path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[7].children[0].children[0]",
                                        text: "行先場所住所",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "TextField_rp08iqrc",
                                        type: "TextField",
                                        path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[7].children[0].children[1]",
                                        text: "東京都港区六本木1-2-3　○○ビル 3F",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_hiequ942",
                                type: "Row",
                                path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[8]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_id3ozmrc",
                                    type: "Column",
                                    path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[8].children[0]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_clg6ft68",
                                        type: "Text",
                                        path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[8].children[0].children[0]",
                                        text: "待ち合わせ場所",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "TextField_rgj370x1",
                                        type: "TextField",
                                        path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[8].children[0].children[1]",
                                        text: "東京都港区六本木1-2-3　○○ビル 3F",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_2xq8snzh",
                                type: "Row",
                                path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[9]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_43zvhthe",
                                    type: "Column",
                                    path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[9].children[0]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_flihzbid",
                                        type: "Text",
                                        path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[9].children[0].children[0]",
                                        text: "グループお誘い希望",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "SwitchListTile_8u4clxfz",
                                        type: "SwitchListTile",
                                        path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[9].children[0].children[1]",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_p7lrty4m",
                                type: "Row",
                                path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[10]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_9orrr0gj",
                                    type: "Column",
                                    path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[10].children[0]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_35s37nym",
                                        type: "Text",
                                        path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[10].children[0].children[0]",
                                        text: "グループお誘い希望人数",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "DropDown_5bq2jjwz",
                                        type: "DropDown",
                                        path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[10].children[0].children[1]",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_y5dnah05",
                                type: "Row",
                                path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[11]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_ry004ma3",
                                    type: "Column",
                                    path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[11].children[0]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_2jo5hvzn",
                                        type: "Text",
                                        path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[11].children[0].children[0]",
                                        text: "お誘い目的（食事等）",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "DropDown_28jgr18w",
                                        type: "DropDown",
                                        path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[11].children[0].children[1]",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_8aeejqf8",
                                type: "Row",
                                path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[12]",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_a02bn5k6",
                                    type: "Column",
                                    path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[12].children[0]",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_65b3a7m6",
                                        type: "Text",
                                        path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[12].children[0].children[0]",
                                        text: "お誘い内容詳細",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "TextField_5xuym89f",
                                        type: "TextField",
                                        path: "ReservationForm.body[0].children[0].children[2].children[0].children[0].children[12].children[0].children[1]",
                                        text: "六本木で、みんなで焼肉でも食べに行きませんか？\nこちらは3人いるので、お友達を誘ってグループでの参加もOK！\nもちろん一人での参加も大丈夫です！",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Row_yc9tgr1m",
                    type: "Row",
                    path: "ReservationForm.body[0].children[0].children[3]",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Button_hzb6mzvi",
                        type: "Button",
                        path: "ReservationForm.body[0].children[0].children[3].children[0]",
                        text: "合流報告",
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

