// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final serviceAreaMunicipalitiesPageHandle = ffai.ProjectPageHandle<ServiceAreaMunicipalitiesPageParams, ServiceAreaMunicipalitiesPageState>(
  name: "ServiceAreaMunicipalitiesPage",
  key: "Scaffold_by7f3bpd",
  route: "admin-service-area-municipalities",
  params: const ServiceAreaMunicipalitiesPageParams(),
  state: const ServiceAreaMunicipalitiesPageState(),
  widgets: ServiceAreaMunicipalitiesPageWidgets.tree,
);

final class ServiceAreaMunicipalitiesPageParams {
  const ServiceAreaMunicipalitiesPageParams();
}

final class ServiceAreaMunicipalitiesPageState {
  const ServiceAreaMunicipalitiesPageState();
  ffai.ProjectStateFieldHandle get municipalitiesList =>
      const ffai.ProjectStateFieldHandle(
        name: "municipalitiesList",
        key: "vdva792f",
        typeName: "List<String>",
      );
  ffai.ProjectStateFieldHandle get municipalityPrefecture =>
      const ffai.ProjectStateFieldHandle(
        name: "municipalityPrefecture",
        key: "epowkk99",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get newMunicipalityLat =>
      const ffai.ProjectStateFieldHandle(
        name: "newMunicipalityLat",
        key: "hsoa82p2",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get newMunicipalityLng =>
      const ffai.ProjectStateFieldHandle(
        name: "newMunicipalityLng",
        key: "9hykyecs",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get newMunicipalityName =>
      const ffai.ProjectStateFieldHandle(
        name: "newMunicipalityName",
        key: "durdwoa5",
        typeName: "String",
      );
}

abstract final class ServiceAreaMunicipalitiesPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_by7f3bpd",
      type: "Scaffold",
      path: "ServiceAreaMunicipalitiesPage",
      name: "ServiceAreaMunicipalitiesPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_7x9wrr5e",
            type: "AppBar",
            path: "ServiceAreaMunicipalitiesPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_mfbjqggo",
                  type: "Text",
                  path: "ServiceAreaMunicipalitiesPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "市区町村マスタ管理",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_zqd8ifrt",
            type: "Column",
            path: "ServiceAreaMunicipalitiesPage.body[0]",
            name: "ServiceAreaMunicipalitiesColumn",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_pu2jqq3k",
                type: "Container",
                path: "ServiceAreaMunicipalitiesPage.body[0].children[0]",
                name: "ServiceAreaMunicipalitiesAccentBar",
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_cejx4nez",
                type: "Text",
                path: "ServiceAreaMunicipalitiesPage.body[0].children[1]",
                name: "Text",
                text: "対象の都道府県名（東京都・神奈川県・千葉県・愛知県・京都府・大阪府・兵庫県・岡山県・広島県・福岡県のいずれか）を入力してください。",
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_gf328g5h",
                type: "TextField",
                path: "ServiceAreaMunicipalitiesPage.body[0].children[2]",
                name: "MunicipalityPrefectureField",
                text: "都道府県",
                triggers: const <String>[
                  "ON_TEXTFIELD_CHANGE",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_pq95ymja",
                type: "Button",
                path: "ServiceAreaMunicipalitiesPage.body[0].children[3]",
                name: "AdminLoadMunicipalitiesButton",
                text: "市区町村一覧を読み込む",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Divider_ez7nrlk4",
                type: "Divider",
                path: "ServiceAreaMunicipalitiesPage.body[0].children[4]",
                name: "Divider",
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_rs756fnu",
                type: "Container",
                path: "ServiceAreaMunicipalitiesPage.body[0].children[5]",
                name: "Container",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_dkmi78lq",
                    type: "Row",
                    path: "ServiceAreaMunicipalitiesPage.body[0].children[5].children[0]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_6x3klzxq",
                        type: "Container",
                        path: "ServiceAreaMunicipalitiesPage.body[0].children[5].children[0].children[0]",
                        name: "Container",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_82cwbm22",
                        type: "Row",
                        path: "ServiceAreaMunicipalitiesPage.body[0].children[5].children[0].children[1]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_49qi8gbi",
                            type: "Icon",
                            path: "ServiceAreaMunicipalitiesPage.body[0].children[5].children[0].children[1].children[0]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_s5sojh49",
                            type: "Text",
                            path: "ServiceAreaMunicipalitiesPage.body[0].children[5].children[0].children[1].children[1]",
                            name: "Text",
                            text: "新しい市区町村を追加",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_t20h4fdq",
                type: "TextField",
                path: "ServiceAreaMunicipalitiesPage.body[0].children[6]",
                name: "NewMunicipalityNameField",
                text: "市区町村名（例: 渋谷区）",
                triggers: const <String>[
                  "ON_TEXTFIELD_CHANGE",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_60wl4gap",
                type: "TextField",
                path: "ServiceAreaMunicipalitiesPage.body[0].children[7]",
                name: "NewMunicipalityLatField",
                text: "緯度（例: 35.6580）",
                triggers: const <String>[
                  "ON_TEXTFIELD_CHANGE",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_tvu378qo",
                type: "TextField",
                path: "ServiceAreaMunicipalitiesPage.body[0].children[8]",
                name: "NewMunicipalityLngField",
                text: "経度（例: 139.7016）",
                triggers: const <String>[
                  "ON_TEXTFIELD_CHANGE",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_fuc1dn8f",
                type: "Button",
                path: "ServiceAreaMunicipalitiesPage.body[0].children[9]",
                name: "AdminAddMunicipalityButton",
                text: "追加",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Divider_v55kc201",
                type: "Divider",
                path: "ServiceAreaMunicipalitiesPage.body[0].children[10]",
                name: "Divider",
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_58zzit94",
                type: "Container",
                path: "ServiceAreaMunicipalitiesPage.body[0].children[11]",
                name: "Container",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_cps451tm",
                    type: "Row",
                    path: "ServiceAreaMunicipalitiesPage.body[0].children[11].children[0]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_9gv5ep4n",
                        type: "Container",
                        path: "ServiceAreaMunicipalitiesPage.body[0].children[11].children[0].children[0]",
                        name: "Container",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_cbtonu0a",
                        type: "Row",
                        path: "ServiceAreaMunicipalitiesPage.body[0].children[11].children[0].children[1]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_vq7cz2ss",
                            type: "Icon",
                            path: "ServiceAreaMunicipalitiesPage.body[0].children[11].children[0].children[1].children[0]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_bv8m84ru",
                            type: "Text",
                            path: "ServiceAreaMunicipalitiesPage.body[0].children[11].children[0].children[1].children[1]",
                            name: "Text",
                            text: "登録済みの市区町村",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_gxztdcus",
                type: "ListView",
                path: "ServiceAreaMunicipalitiesPage.body[0].children[12]",
                name: "MunicipalitiesListView",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Card_s14ttyvj",
                    type: "Card",
                    path: "ServiceAreaMunicipalitiesPage.body[0].children[12].children[0]",
                    name: "Card",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_hxjav3om",
                        type: "Container",
                        path: "ServiceAreaMunicipalitiesPage.body[0].children[12].children[0].children[0]",
                        name: "Container",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_nrtwwnhn",
                            type: "Row",
                            path: "ServiceAreaMunicipalitiesPage.body[0].children[12].children[0].children[0].children[0]",
                            name: "MunicipalityRow",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_3kdoemqk",
                                type: "Row",
                                path: "ServiceAreaMunicipalitiesPage.body[0].children[12].children[0].children[0].children[0].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_8ow70yr7",
                                    type: "Icon",
                                    path: "ServiceAreaMunicipalitiesPage.body[0].children[12].children[0].children[0].children[0].children[0].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_epdaa2a1",
                                    type: "Text",
                                    path: "ServiceAreaMunicipalitiesPage.body[0].children[12].children[0].children[0].children[0].children[0].children[1]",
                                    name: "Text",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Button_8bsa9dca",
                                type: "Button",
                                path: "ServiceAreaMunicipalitiesPage.body[0].children[12].children[0].children[0].children[0].children[1]",
                                name: "AdminRemoveMunicipalityButton",
                                text: "削除",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

