// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final settingsPageHandle = ffai.ProjectPageHandle<SettingsPageParams, SettingsPageState>(
  name: "SettingsPage",
  key: "Scaffold_osfb9440",
  route: "settings",
  params: const SettingsPageParams(),
  state: const SettingsPageState(),
  widgets: SettingsPageWidgets.tree,
);

final class SettingsPageParams {
  const SettingsPageParams();
}

final class SettingsPageState {
  const SettingsPageState();
}

abstract final class SettingsPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_osfb9440",
      type: "Scaffold",
      path: "SettingsPage",
      name: "SettingsPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_bjtoykxf",
            type: "AppBar",
            path: "SettingsPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_lztjj4el",
                  type: "Text",
                  path: "SettingsPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "設定",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_0dh902o6",
            type: "Column",
            path: "SettingsPage.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Text_4ytmp7l4",
                type: "Text",
                path: "SettingsPage.body[0].children[0]",
                name: "Text",
                text: "アカウントを削除する",
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_2pl7t6r3",
                type: "Text",
                path: "SettingsPage.body[0].children[1]",
                name: "Text",
                text: "論理負債がある場合、進行中の予約がある場合、または送金処理中の台帳がある場合は退会できません。",
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_3o5egwdb",
                type: "Button",
                path: "SettingsPage.body[0].children[2]",
                name: "Button",
                text: "退会する",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

