// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final signupPageHandle = ffai.ProjectPageHandle<SignupPageParams, SignupPageState>(
  name: "SignupPage",
  key: "Scaffold_algo83hc",
  route: "",
  params: const SignupPageParams(),
  state: const SignupPageState(),
  widgets: SignupPageWidgets.tree,
);

final class SignupPageParams {
  const SignupPageParams();
}

final class SignupPageState {
  const SignupPageState();
}

abstract final class SignupPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_algo83hc",
      type: "Scaffold",
      path: "SignupPage",
      name: "SignupPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_7ffs1kh2",
            type: "AppBar",
            path: "SignupPage.appBar[0]",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Row_g3hn8set",
                  type: "Row",
                  path: "SignupPage.appBar[0].title[0]",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Image_vr3j2tmr",
                      type: "Image",
                      path: "SignupPage.appBar[0].title[0].children[0]",
                    ),
                  ],
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_0f5kj9nh",
            type: "Container",
            path: "SignupPage.body[0]",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Form_m8n7ql1q",
                type: "Form",
                path: "SignupPage.body[0].children[0]",
                name: "SignupPageForm",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_1l11coyc",
                    type: "Column",
                    path: "SignupPage.body[0].children[0].children[0]",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_7uknh537",
                        type: "Text",
                        path: "SignupPage.body[0].children[0].children[0].children[0]",
                        text: "新規登録",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "TextField_jwk8t621",
                        type: "TextField",
                        path: "SignupPage.body[0].children[0].children[0].children[1]",
                        name: "NicknameField",
                        text: "ニックネーム",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "TextField_f8b7o6cv",
                        type: "TextField",
                        path: "SignupPage.body[0].children[0].children[0].children[2]",
                        name: "SignupEmailField",
                        text: "メールアドレス",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "TextField_pl4vg1o3",
                        type: "TextField",
                        path: "SignupPage.body[0].children[0].children[0].children[3]",
                        name: "SignupPasswordField",
                        text: "パスワード",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "TextField_auj08iok",
                        type: "TextField",
                        path: "SignupPage.body[0].children[0].children[0].children[4]",
                        name: "SignupConfirmField",
                        text: "パスワード 確認",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_pvdj8fqh",
                        type: "Row",
                        path: "SignupPage.body[0].children[0].children[0].children[5]",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_4iaixins",
                            type: "Text",
                            path: "SignupPage.body[0].children[0].children[0].children[5].children[0]",
                            text: "利用規約類を確認及び同意しました",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Checkbox_lu3okidh",
                            type: "Checkbox",
                            path: "SignupPage.body[0].children[0].children[0].children[5].children[1]",
                            triggers: const <String>[
                              "ON_TOGGLE_ON",
                              "ON_TOGGLE_OFF",
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_s8s3l7kd",
                        type: "Button",
                        path: "SignupPage.body[0].children[0].children[0].children[6]",
                        text: "新規登録",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_ia6k5xrf",
                        type: "Text",
                        path: "SignupPage.body[0].children[0].children[0].children[7]",
                        text: "ログインの方はこちらからどうぞ",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

