// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final smsCodeHandle = ffai.ProjectPageHandle<SmsCodeParams, SmsCodeState>(
  name: "SmsCode",
  key: "Scaffold_ru0dbklw",
  route: "",
  params: const SmsCodeParams(),
  state: const SmsCodeState(),
  widgets: SmsCodeWidgets.tree,
);

final class SmsCodeParams {
  const SmsCodeParams();
}

final class SmsCodeState {
  const SmsCodeState();
}

abstract final class SmsCodeWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_ru0dbklw",
      type: "Scaffold",
      path: "SmsCode",
      name: "SmsCode",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_67girqn0",
            type: "AppBar",
            path: "SmsCode.appBar[0]",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Row_q4xvry2a",
                  type: "Row",
                  path: "SmsCode.appBar[0].title[0]",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Image_eikhrkz7",
                      type: "Image",
                      path: "SmsCode.appBar[0].title[0].children[0]",
                      triggers: const <String>[
                        "ON_TAP",
                      ],
                    ),
                  ],
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_e69o6iui",
            type: "Container",
            path: "SmsCode.body[0]",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_lbczybpd",
                type: "Column",
                path: "SmsCode.body[0].children[0]",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_105oqvgg",
                    type: "Container",
                    path: "SmsCode.body[0].children[0].children[0]",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Image_jwl544iu",
                        type: "Image",
                        path: "SmsCode.body[0].children[0].children[0].children[0]",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_hvplaek0",
                    type: "Text",
                    path: "SmsCode.body[0].children[0].children[1]",
                    text: "SMS認証コードを確認してください",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_9xjfvk12",
                    type: "Text",
                    path: "SmsCode.body[0].children[0].children[2]",
                    text: "SMSコードを入力してください",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Card_ds9bsiu0",
                    type: "Card",
                    path: "SmsCode.body[0].children[0].children[3]",
                    name: "SmsCodeCard",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_t2q0szwl",
                        type: "Container",
                        path: "SmsCode.body[0].children[0].children[3].children[0]",
                        name: "Container",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "TextField_hwayoyv5",
                            type: "TextField",
                            path: "SmsCode.body[0].children[0].children[3].children[0].children[0]",
                            name: "SmsCodeField",
                            text: "SMS認証コード",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_ird0t981",
                    type: "Container",
                    path: "SmsCode.body[0].children[0].children[4]",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_5k57pqob",
                        type: "Column",
                        path: "SmsCode.body[0].children[0].children[4].children[0]",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_qmqp39eo",
                            type: "Row",
                            path: "SmsCode.body[0].children[0].children[4].children[0].children[0]",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_jpctiv4n",
                                type: "Icon",
                                path: "SmsCode.body[0].children[0].children[4].children[0].children[0].children[0]",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_0exgytx5",
                                type: "Text",
                                path: "SmsCode.body[0].children[0].children[4].children[0].children[0].children[1]",
                                text: "コードの有効期限は10分です\n届かない場合は再送してください",
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_ynhflo1r",
                    type: "Button",
                    path: "SmsCode.body[0].children[0].children[5]",
                    text: "認証する",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_lo5jbbia",
                    type: "Button",
                    path: "SmsCode.body[0].children[0].children[6]",
                    text: "認証コードを再送する",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

