// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final stripeLogsPageHandle = ffai.ProjectPageHandle<StripeLogsPageParams, StripeLogsPageState>(
  name: "StripeLogsPage",
  key: "Scaffold_p0wvop0f",
  route: "admin-stripe-logs",
  params: const StripeLogsPageParams(),
  state: const StripeLogsPageState(),
  widgets: StripeLogsPageWidgets.tree,
);

final class StripeLogsPageParams {
  const StripeLogsPageParams();
}

final class StripeLogsPageState {
  const StripeLogsPageState();
  ffai.ProjectStateFieldHandle get adminStripeLogsList =>
      const ffai.ProjectStateFieldHandle(
        name: "adminStripeLogsList",
        key: "ukl7xmeh",
        typeName: "List<String>",
      );
}

abstract final class StripeLogsPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_p0wvop0f",
      type: "Scaffold",
      path: "StripeLogsPage",
      name: "StripeLogsPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_qthrv9ed",
            type: "AppBar",
            path: "StripeLogsPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_dr4zp8dh",
                  type: "Text",
                  path: "StripeLogsPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Stripeログ",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "ListView_3rjbmrnk",
            type: "ListView",
            path: "StripeLogsPage.body[0]",
            name: "AdminStripeLogsListView",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Card_n02z66nh",
                type: "Card",
                path: "StripeLogsPage.body[0].children[0]",
                name: "Card",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_atuc6239",
                    type: "Container",
                    path: "StripeLogsPage.body[0].children[0].children[0]",
                    name: "Container",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_k5qsmv5p",
                        type: "Column",
                        path: "StripeLogsPage.body[0].children[0].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_nut0pkpx",
                            type: "Text",
                            path: "StripeLogsPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Text",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Button_nzq8zr8m",
                            type: "Button",
                            path: "StripeLogsPage.body[0].children[0].children[0].children[0].children[1]",
                            name: "Button",
                            text: "生データを見る",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

