// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final supportLegalHubHandle = ffai.ProjectPageHandle<SupportLegalHubParams, SupportLegalHubState>(
  name: "SupportLegalHub",
  key: "Scaffold_51befgfu",
  route: "support-legal",
  params: const SupportLegalHubParams(),
  state: const SupportLegalHubState(),
  widgets: SupportLegalHubWidgets.tree,
);

final class SupportLegalHubParams {
  const SupportLegalHubParams();
}

final class SupportLegalHubState {
  const SupportLegalHubState();
}

abstract final class SupportLegalHubWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_51befgfu",
      type: "Scaffold",
      path: "SupportLegalHub",
      name: "SupportLegalHub",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_4h43sliv",
            type: "AppBar",
            path: "SupportLegalHub.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_w7hq6ogs",
                  type: "Text",
                  path: "SupportLegalHub.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "サポート・法的項目",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_wutn42f4",
            type: "Column",
            path: "SupportLegalHub.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Card_xz53b6hc",
                type: "Card",
                path: "SupportLegalHub.body[0].children[0]",
                name: "TermsOfServiceRow",
                triggers: const <String>[
                  "ON_TAP",
                ],
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_wktruogh",
                    type: "Row",
                    path: "SupportLegalHub.body[0].children[0].children[0]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Icon_a352mqui",
                        type: "Icon",
                        path: "SupportLegalHub.body[0].children[0].children[0].children[0]",
                        name: "Icon",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_yqfwiqi8",
                        type: "Text",
                        path: "SupportLegalHub.body[0].children[0].children[0].children[1]",
                        name: "Text",
                        text: "利用規約",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Icon_0qqukli1",
                        type: "Icon",
                        path: "SupportLegalHub.body[0].children[0].children[0].children[2]",
                        name: "Icon",
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Card_mzg1y0hj",
                type: "Card",
                path: "SupportLegalHub.body[0].children[1]",
                name: "PrivacyPolicyRow",
                triggers: const <String>[
                  "ON_TAP",
                ],
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_6hqiqaji",
                    type: "Row",
                    path: "SupportLegalHub.body[0].children[1].children[0]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Icon_s8kscdvy",
                        type: "Icon",
                        path: "SupportLegalHub.body[0].children[1].children[0].children[0]",
                        name: "Icon",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_az8rwdxj",
                        type: "Text",
                        path: "SupportLegalHub.body[0].children[1].children[0].children[1]",
                        name: "Text",
                        text: "プライバシーポリシー",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Icon_vzyxpp4d",
                        type: "Icon",
                        path: "SupportLegalHub.body[0].children[1].children[0].children[2]",
                        name: "Icon",
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Card_hcc8tp7x",
                type: "Card",
                path: "SupportLegalHub.body[0].children[2]",
                name: "InquiryFormRow",
                triggers: const <String>[
                  "ON_TAP",
                ],
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_i1xhnst7",
                    type: "Row",
                    path: "SupportLegalHub.body[0].children[2].children[0]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Image_8sags9q3",
                        type: "Image",
                        path: "SupportLegalHub.body[0].children[2].children[0].children[0]",
                        name: "Image",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_9v4ymfjm",
                        type: "Text",
                        path: "SupportLegalHub.body[0].children[2].children[0].children[1]",
                        name: "Text",
                        text: "お問い合わせ",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Icon_0t65vcp3",
                        type: "Icon",
                        path: "SupportLegalHub.body[0].children[2].children[0].children[2]",
                        name: "Icon",
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

