// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final userManagementPageHandle = ffai.ProjectPageHandle<UserManagementPageParams, UserManagementPageState>(
  name: "UserManagementPage",
  key: "Scaffold_ev3fl2sy",
  route: "admin-users",
  params: const UserManagementPageParams(),
  state: const UserManagementPageState(),
  widgets: UserManagementPageWidgets.tree,
);

final class UserManagementPageParams {
  const UserManagementPageParams();
}

final class UserManagementPageState {
  const UserManagementPageState();
  ffai.ProjectStateFieldHandle get adminUsersList =>
      const ffai.ProjectStateFieldHandle(
        name: "adminUsersList",
        key: "fyvf8s5y",
        typeName: "List<String>",
      );
}

abstract final class UserManagementPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_ev3fl2sy",
      type: "Scaffold",
      path: "UserManagementPage",
      name: "UserManagementPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_osogcvlu",
            type: "AppBar",
            path: "UserManagementPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_7jw6nunf",
                  type: "Text",
                  path: "UserManagementPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "ユーザー管理",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_auxgo8p6",
            type: "Column",
            path: "UserManagementPage.body[0]",
            name: "AdminUsersWithExportColumn",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_s5np940x",
                type: "Container",
                path: "UserManagementPage.body[0].children[0]",
                name: "UserManagementAccentBar",
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_9qfj01oh",
                type: "Button",
                path: "UserManagementPage.body[0].children[1]",
                name: "AdminExportUsersCsvButton",
                text: "CSVをコピー（読み込み済みの行のみ）",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Divider_x9b5uvyv",
                type: "Divider",
                path: "UserManagementPage.body[0].children[2]",
                name: "Divider",
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_nfahhob2",
                type: "ListView",
                path: "UserManagementPage.body[0].children[3]",
                name: "AdminUsersListView",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Card_n8oobfkk",
                    type: "Card",
                    path: "UserManagementPage.body[0].children[3].children[0]",
                    name: "Card",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_klpraqx1",
                        type: "Container",
                        path: "UserManagementPage.body[0].children[3].children[0].children[0]",
                        name: "Container",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_4lyfp08o",
                            type: "Column",
                            path: "UserManagementPage.body[0].children[3].children[0].children[0].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_ttzki70a",
                                type: "Row",
                                path: "UserManagementPage.body[0].children[3].children[0].children[0].children[0].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_opu9omdd",
                                    type: "Icon",
                                    path: "UserManagementPage.body[0].children[3].children[0].children[0].children[0].children[0].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_ndybetlb",
                                    type: "Row",
                                    path: "UserManagementPage.body[0].children[3].children[0].children[0].children[0].children[0].children[1]",
                                    name: "Row",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_93p6qyuk",
                                        type: "Row",
                                        path: "UserManagementPage.body[0].children[3].children[0].children[0].children[0].children[0].children[1].children[0]",
                                        name: "Row",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_e2r6kpql",
                                            type: "Icon",
                                            path: "UserManagementPage.body[0].children[3].children[0].children[0].children[0].children[0].children[1].children[0].children[0]",
                                            name: "Icon",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_pcft62ow",
                                            type: "Text",
                                            path: "UserManagementPage.body[0].children[3].children[0].children[0].children[0].children[0].children[1].children[0].children[1]",
                                            name: "Text",
                                            text: "凍結中",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_xj2u9mis",
                                        type: "Container",
                                        path: "UserManagementPage.body[0].children[3].children[0].children[0].children[0].children[0].children[1].children[1]",
                                        name: "ApprovalStatusBadge",
                                        componentName: "ApprovalStatusBadge",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_qu20ootl",
                                type: "Text",
                                path: "UserManagementPage.body[0].children[3].children[0].children[0].children[0].children[1]",
                                name: "Text",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_qyliau37",
                                type: "Row",
                                path: "UserManagementPage.body[0].children[3].children[0].children[0].children[0].children[2]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_iktatup4",
                                    type: "Button",
                                    path: "UserManagementPage.body[0].children[3].children[0].children[0].children[0].children[2].children[0]",
                                    name: "AdminToggleFreezeButton",
                                    text: "凍結/解除",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_pefmgi5c",
                                    type: "Button",
                                    path: "UserManagementPage.body[0].children[3].children[0].children[0].children[0].children[2].children[1]",
                                    name: "AdminForceDeleteButton",
                                    text: "強制退会",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Button_2kfxrnci",
                                type: "Button",
                                path: "UserManagementPage.body[0].children[3].children[0].children[0].children[0].children[3]",
                                name: "AdminContentModerationNavButton",
                                text: "コンテンツ管理",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Button_t9u9zb82",
                                type: "Button",
                                path: "UserManagementPage.body[0].children[3].children[0].children[0].children[0].children[4]",
                                name: "AdminDeletionMonitorNavButton",
                                text: "退会ブロック状況",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Button_kxqs1h29",
                                type: "Button",
                                path: "UserManagementPage.body[0].children[3].children[0].children[0].children[0].children[5]",
                                name: "AdminConsentRecordNavButton",
                                text: "同意記録",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

