// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final userManagementPageHandle = ffai.ProjectPageHandle<UserManagementPageParams, UserManagementPageState>(
  name: "UserManagementPage",
  key: "Scaffold_ev3fl2sy",
  route: "admin-users",
  params: const UserManagementPageParams(),
  state: const UserManagementPageState(),
  widgets: UserManagementPageWidgets.tree,
);

final class UserManagementPageParams {
  const UserManagementPageParams();
}

final class UserManagementPageState {
  const UserManagementPageState();
  ffai.ProjectStateFieldHandle get adminUsersList =>
      const ffai.ProjectStateFieldHandle(
        name: "adminUsersList",
        key: "fyvf8s5y",
        typeName: "List<String>",
      );
}

abstract final class UserManagementPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_ev3fl2sy",
      type: "Scaffold",
      path: "UserManagementPage",
      name: "UserManagementPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_osogcvlu",
            type: "AppBar",
            path: "UserManagementPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_7jw6nunf",
                  type: "Text",
                  path: "UserManagementPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "ユーザー管理",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_auxgo8p6",
            type: "Column",
            path: "UserManagementPage.body[0]",
            name: "AdminUsersWithExportColumn",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Button_rmjkvlp5",
                type: "Button",
                path: "UserManagementPage.body[0].children[0]",
                name: "AdminExportUsersCsvButton",
                text: "CSVをコピー（読み込み済みの行のみ）",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Divider_b636u8pm",
                type: "Divider",
                path: "UserManagementPage.body[0].children[1]",
                name: "Divider",
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_30cxhdgf",
                type: "ListView",
                path: "UserManagementPage.body[0].children[2]",
                name: "AdminUsersListView",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Card_9v23nz0w",
                    type: "Card",
                    path: "UserManagementPage.body[0].children[2].children[0]",
                    name: "Card",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_w4o774ai",
                        type: "Container",
                        path: "UserManagementPage.body[0].children[2].children[0].children[0]",
                        name: "Container",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_fxhotqj5",
                            type: "Column",
                            path: "UserManagementPage.body[0].children[2].children[0].children[0].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_dxiqaufe",
                                type: "Text",
                                path: "UserManagementPage.body[0].children[2].children[0].children[0].children[0].children[0]",
                                name: "Text",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_gc24auj8",
                                type: "Row",
                                path: "UserManagementPage.body[0].children[2].children[0].children[0].children[0].children[1]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_i0un4j6a",
                                    type: "Button",
                                    path: "UserManagementPage.body[0].children[2].children[0].children[0].children[0].children[1].children[0]",
                                    name: "AdminToggleFreezeButton",
                                    text: "凍結/解除",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_2triya65",
                                    type: "Button",
                                    path: "UserManagementPage.body[0].children[2].children[0].children[0].children[0].children[1].children[1]",
                                    name: "AdminForceDeleteButton",
                                    text: "強制退会",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Button_usce4q4u",
                                type: "Button",
                                path: "UserManagementPage.body[0].children[2].children[0].children[0].children[0].children[2]",
                                name: "AdminContentModerationNavButton",
                                text: "コンテンツ管理",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Button_povonv92",
                                type: "Button",
                                path: "UserManagementPage.body[0].children[2].children[0].children[0].children[0].children[3]",
                                name: "AdminDeletionMonitorNavButton",
                                text: "退会ブロック状況",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Button_7ir3rwq8",
                                type: "Button",
                                path: "UserManagementPage.body[0].children[2].children[0].children[0].children[0].children[4]",
                                name: "AdminConsentRecordNavButton",
                                text: "同意記録",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

