// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final workPostDetailPageHandle = ffai.ProjectPageHandle<WorkPostDetailPageParams, WorkPostDetailPageState>(
  name: "WorkPostDetailPage",
  key: "Scaffold_ti3w8a2w",
  route: "work-post-detail",
  params: const WorkPostDetailPageParams(),
  state: const WorkPostDetailPageState(),
  widgets: WorkPostDetailPageWidgets.tree,
);

final class WorkPostDetailPageParams {
  const WorkPostDetailPageParams();
  ffai.ProjectParamHandle get postId =>
      const ffai.ProjectParamHandle(
        name: "postId",
        key: "qlszg2b0",
        typeName: "String",
      );
}

final class WorkPostDetailPageState {
  const WorkPostDetailPageState();
  ffai.ProjectStateFieldHandle get applicantsList =>
      const ffai.ProjectStateFieldHandle(
        name: "applicantsList",
        key: "rp9e2zjc",
        typeName: "List<String>",
      );
  ffai.ProjectStateFieldHandle get detailData =>
      const ffai.ProjectStateFieldHandle(
        name: "detailData",
        key: "oqvas916",
        typeName: "String",
      );
}

abstract final class WorkPostDetailPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_ti3w8a2w",
      type: "Scaffold",
      path: "WorkPostDetailPage",
      name: "WorkPostDetailPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_vmxum81q",
            type: "AppBar",
            path: "WorkPostDetailPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_b6tgt8kk",
                  type: "Text",
                  path: "WorkPostDetailPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "ワーク詳細",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_e2rsqq9y",
            type: "Column",
            path: "WorkPostDetailPage.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Text_d5tfolju",
                type: "Text",
                path: "WorkPostDetailPage.body[0].children[0]",
                name: "Text",
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_xn8775zl",
                type: "Text",
                path: "WorkPostDetailPage.body[0].children[1]",
                name: "Text",
              ),
              ffai.ProjectWidgetHandle(
                key: "Row_klr6dwca",
                type: "Row",
                path: "WorkPostDetailPage.body[0].children[2]",
                name: "Row",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_q1v2mh4n",
                    type: "Text",
                    path: "WorkPostDetailPage.body[0].children[2].children[0]",
                    name: "Text",
                    text: "日付：",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_o8rdw77l",
                    type: "Text",
                    path: "WorkPostDetailPage.body[0].children[2].children[1]",
                    name: "Text",
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Row_fts7r5ux",
                type: "Row",
                path: "WorkPostDetailPage.body[0].children[3]",
                name: "Row",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_rbakpuy9",
                    type: "Text",
                    path: "WorkPostDetailPage.body[0].children[3].children[0]",
                    name: "Text",
                    text: "場所：",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_y3iuwryy",
                    type: "Text",
                    path: "WorkPostDetailPage.body[0].children[3].children[1]",
                    name: "Text",
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Row_yjvomqwx",
                type: "Row",
                path: "WorkPostDetailPage.body[0].children[4]",
                name: "Row",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_deoitse7",
                    type: "Text",
                    path: "WorkPostDetailPage.body[0].children[4].children[0]",
                    name: "Text",
                    text: "報酬：",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_m5up531p",
                    type: "Text",
                    path: "WorkPostDetailPage.body[0].children[4].children[1]",
                    name: "Text",
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Row_en59wyik",
                type: "Row",
                path: "WorkPostDetailPage.body[0].children[5]",
                name: "Row",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_pp0u59bo",
                    type: "Text",
                    path: "WorkPostDetailPage.body[0].children[5].children[0]",
                    name: "Text",
                    text: "状態：",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_5x2h0o7c",
                    type: "Text",
                    path: "WorkPostDetailPage.body[0].children[5].children[1]",
                    name: "Text",
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Row_lv9s8i49",
                type: "Row",
                path: "WorkPostDetailPage.body[0].children[6]",
                name: "Row",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_56aii1o6",
                    type: "Text",
                    path: "WorkPostDetailPage.body[0].children[6].children[0]",
                    name: "Text",
                    text: "投稿者：",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_zl2rigba",
                    type: "Text",
                    path: "WorkPostDetailPage.body[0].children[6].children[1]",
                    name: "Text",
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Divider_3zwjg5hk",
                type: "Divider",
                path: "WorkPostDetailPage.body[0].children[7]",
                name: "Divider",
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_jaw63ext",
                type: "Button",
                path: "WorkPostDetailPage.body[0].children[8]",
                name: "Button",
                text: "応募する",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_hac41pdt",
                type: "Text",
                path: "WorkPostDetailPage.body[0].children[9]",
                name: "Text",
                text: "応募済みです。",
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_vzqqarab",
                type: "Text",
                path: "WorkPostDetailPage.body[0].children[10]",
                name: "Text",
                text: "応募者一覧",
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_9xkyi08s",
                type: "ListView",
                path: "WorkPostDetailPage.body[0].children[11]",
                name: "WorkPostApplicantsListView",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_h3jpdkvt",
                    type: "Row",
                    path: "WorkPostDetailPage.body[0].children[11].children[0]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_oty2ekiz",
                        type: "Text",
                        path: "WorkPostDetailPage.body[0].children[11].children[0].children[0]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_puhug8da",
                        type: "Button",
                        path: "WorkPostDetailPage.body[0].children[11].children[0].children[1]",
                        name: "Button",
                        text: "選定する",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

