// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

abstract final class AppState {
  static const checkBox = ffai.ProjectAppStateFieldHandle(
    name: "checkBox",
    key: "7fyhn9sb",
    typeName: "Boolean",
    persisted: false,
  );
  static const currentFilter = ffai.ProjectAppStateFieldHandle(
    name: "currentFilter",
    key: "mce18gjo",
    typeName: "String",
    persisted: false,
  );
  static const currentFilterName = ffai.ProjectAppStateFieldHandle(
    name: "currentFilterName",
    key: "vslbzcai",
    typeName: "String",
    persisted: false,
  );
  static const currentNotificationFilter = ffai.ProjectAppStateFieldHandle(
    name: "currentNotificationFilter",
    key: "ozooh1te",
    typeName: "String",
    persisted: false,
  );
  static const isagreed = ffai.ProjectAppStateFieldHandle(
    name: "isagreed",
    key: "snywgcar",
    typeName: "Boolean",
    persisted: false,
  );
  static const navIndex = ffai.ProjectAppStateFieldHandle(
    name: "navIndex",
    key: "1wxw8xv9",
    typeName: "Integer",
    persisted: false,
  );
  static const pickedActivityPrefectureValue = ffai.ProjectAppStateFieldHandle(
    name: "pickedActivityPrefectureValue",
    key: "tjpognu2",
    typeName: "String",
    persisted: false,
  );
  static const pickedPrefectureValue = ffai.ProjectAppStateFieldHandle(
    name: "pickedPrefectureValue",
    key: "2dubhn7i",
    typeName: "String",
    persisted: false,
  );
  static const prefecturePickList = ffai.ProjectAppStateFieldHandle(
    name: "prefecturePickList",
    key: "31ttgh2e",
    typeName: "List<String>",
    persisted: false,
  );
  static const searchCastKeyword = ffai.ProjectAppStateFieldHandle(
    name: "searchCastKeyword",
    key: "nfqsacwz",
    typeName: "String",
    persisted: false,
  );
  static const searchShopKeyword = ffai.ProjectAppStateFieldHandle(
    name: "searchShopKeyword",
    key: "8b0isjuk",
    typeName: "String",
    persisted: false,
  );
  static const verificationPhoneNumber = ffai.ProjectAppStateFieldHandle(
    name: "verificationPhoneNumber",
    key: "ogjg7oo3",
    typeName: "String",
    persisted: false,
  );
  static const all = <ffai.ProjectAppStateFieldHandle>[
    checkBox,
    currentFilter,
    currentFilterName,
    currentNotificationFilter,
    isagreed,
    navIndex,
    pickedActivityPrefectureValue,
    pickedPrefectureValue,
    prefecturePickList,
    searchCastKeyword,
    searchShopKeyword,
    verificationPhoneNumber,
  ];
}

